package.json, src/components/tags.tsx, src/pages/_app.tsx, src/pages/index.tsx, yarn.lock
Resolves: https://github.com/blockstack/explorer/issues/11
=> Component: Transaction Tags

package.json, src/common/hooks/use-recently-viewed-tx.tsx, src/common/utils.ts, src/components/dev-links.tsx, src/components/home-nav.tsx, src/components/icons/blockstack-logo.tsx, src/components/icons/magnifying-glass.tsx, src/components/page.tsx, src/components/search-bar.tsx, src/pages/api/transactions.ts, src/pages/index.tsx, src/pages/txid/[txid].tsx, tsconfig.json, yarn.lock
I've added the `store` npm package, rather than attempting to use redux-persist. It's a < 1kB package that wraps to string/to object functionality, makes for much more readable code.
Looking for feedback on the hook, this is the first one I've made.
=> feat: scaffold base homepage functionality

package.json, src/common/hooks/use-recently-viewed-tx.tsx, src/common/utils.ts, src/components/home-nav.tsx, src/components/recently-viewed.tsx, src/components/search-bar.tsx, src/components/tags.tsx, src/components/transaction-title.tsx, src/models/transaction.interface.ts, src/pages/components.tsx, src/pages/index.tsx, src/pages/transaction.tsx, src/pages/txid/[txid].tsx, src/store/transactions/actions.ts, src/store/transactions/reducer.ts, yarn.lock
=> feat: add recently viewed component

src/common/search.tsx, src/components/home-nav.tsx, src/components/page.tsx, src/components/search-bar.tsx, src/pages/index.tsx
=> feat: add tx page header

package.json, src/components/dev-links.tsx, src/components/home-nav.tsx, src/components/search-bar.tsx, src/pages/_app.tsx, src/pages/_document.tsx, yarn.lock
=> fix: manage meta tags, improve accessibility

src/components/footer-links.tsx
=> feat: add FAQ to footer

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Add issue templates for release
=> chore: add issue template

src/components/app-init.tsx
Adding Fathom tracking to close #132
=> feat: add-fathom

package.json, src/components/timestamp.tsx, src/components/transaction-details.tsx, yarn.lock
=> feat: adding timestamp tooltip to blocktime row

src/common/hooks/use-lock-body-scroll.tsx, src/components/badge.tsx, src/components/close-button.tsx, src/components/code-accordian.tsx, src/components/contract-card.tsx, src/components/footer.tsx, src/components/header.tsx, src/components/meta-head.tsx, src/components/page.tsx, src/components/popover/popover.tsx, src/components/popover/types.ts, src/components/popover/use-popover.tsx, src/components/post-conditions.tsx, src/components/recently-viewed.tsx, src/components/rows/row.tsx, src/components/search-bar/index.tsx, src/components/token-transfer/index.tsx, src/components/token-transfer/item.tsx, src/components/transaction-details.tsx, src/components/transaction-item.tsx, src/components/tx/coinbase.tsx, src/components/tx/not-found.tsx, src/components/typography.tsx, src/pages/transactions.tsx
This improves the usability on mobile for the search box / drop downs.
=> fix: improve search mobile experience

package.json, src/common/hooks/use-user-session.tsx, src/components/alert.tsx, src/components/footer.tsx, src/components/header.tsx, src/components/page.tsx, src/components/popover/popover.tsx, src/components/popover/use-popover.tsx, src/components/recently-viewed.tsx, src/components/rows/row.tsx, src/components/sandbox/common.tsx, src/components/sandbox/contract-call.tsx, src/components/sandbox/contract-deploy.tsx, src/components/sandbox/faucet.tsx, src/components/sandbox/raw-tx.tsx, src/components/sandbox/tabs.tsx, src/components/sandbox/token-transfer.tsx, src/components/search-bar/index.tsx, src/components/tags.tsx, src/components/tooltip.tsx, src/components/transaction-item.tsx, src/components/tx/contract-call.tsx, src/pages/sandbox/index.tsx, src/pages/transactions.tsx, src/pages/txid/[txid].tsx, src/store/sandbox/actions.ts, yarn.lock
- adds feedback link
- persists key generated with gaia
- updates error messages for failed txs
- updates tx item icon display
- improves tooltip (will update in blockstack/ui)
- small logic bug for popover keyboard navigation
=> general v1.0.0 improvements

README.md
Update DNS record in readme to `stacks-node-api.blockstack.org`
=> update DNS in readme

src/common/api/network.ts, src/common/hooks/use-network-add-form.tsx, src/common/hooks/use-network-mode.ts, src/common/hooks/use-stacks-info.ts, src/common/types/network.ts, src/common/utils.tsx, src/common/utils/addresses.ts, src/components/address-not-found.tsx, src/components/balances/stx-balance-card.tsx, src/components/block-not-found.tsx, src/components/btc-anchor-card.tsx, src/components/function-summary/args.tsx, src/components/metaverse-bg.tsx, src/components/network-items.tsx, src/components/network-mode-banner.tsx, src/components/page.tsx, src/components/stacking.tsx, src/components/stacks-token-vesting-card.tsx, src/components/transaction-list.tsx, src/components/tx-not-found.tsx, src/pages/404.tsx, src/pages/_error.tsx, src/pages/address/[principal].tsx, src/pages/block/[hash].tsx, src/pages/blocks.tsx
This updates the address page to display any pending TXs for the given address.
=> feat: show pending txs on address page

src/components/meta-head.tsx, src/components/metaverse-bg.tsx
=> fix: https imgix

src/common/constants.ts, src/common/utils/addresses.ts, src/components/balances/stx-balance-card.tsx, src/components/blocks-list.tsx, src/components/code-block/code-block.tsx, src/components/contract-source.tsx, src/components/section.tsx, src/pages/block/[hash].tsx
- Updates code blocks to work a bit better
- Better empty state in blocks
- some misc env var changes
=> pre-mainnet fixes

src/common/constants.ts, src/components/notice.tsx, src/components/page.tsx
This adds the ability to display a site wide notice via env vars if needed.
=> feat: site notice

src/components/post-conditions.tsx, yarn.lock
Fixes a bug where stx post conditions were formatted incorrectly.
=> fix: microstx to stx for stx post conditions

src/components/function-summary/result.tsx
=> fix: rendering for tx result list type in tuple

src/components/balances/stx-balance-card.tsx, src/components/stacks-token-vesting-card.tsx, src/components/tx/smart-contract.tsx, src/pages/address/[principal].tsx, yarn.lock
`SM22FHVJRE2KCNF0EXNCD7QMWDD1X46TWHK4EPRK0` - [Address with an unlocking schedule](https://user-images.githubusercontent.com/1109058/106805891-1c9b7680-661c-11eb-9bf4-3be1b79aa1f2.png)
`SP3XYPZWTZ508CEM52K014CDN5VJRRWS1ZGWCQEK9` - [Address with active stacking](https://user-images.githubusercontent.com/1109058/106805991-3dfc6280-661c-11eb-8c1e-f4a68c5a87a7.png)
Todo:
=> fix: add notice to addresses with unlocking

src/components/function-summary/value.tsx
fixes https://github.com/blockstack/explorer/issues/382
=> fix: better checking for tuples

src/pages/blocks.tsx
This PR
* changes the title in Recent Blocks to exactly that
=> fix: use correct title in meta

src/common/constants.ts, src/common/hooks/use-fathom.ts, src/components/app-container.tsx, src/pages/_app.tsx, src/sandbox/components/screens/call-functions/components/available-functions.tsx, src/sandbox/components/screens/call-functions/components/contract-search.tsx, src/sandbox/components/screens/write-deploy/tools-panel.tsx, src/sandbox/components/views/faucet.tsx, src/sandbox/components/views/token-transfer.tsx, src/sandbox/hooks/use-connect.tsx, src/sandbox/index.tsx
This fixes fathom to actually work. Something was up before where it wasn't registering correctly.
=> fix: fathom

src/components/page.tsx
=> feat: garbage collection note

src/common/hooks/use-network-config.tsx, src/sandbox/components/screens/call-functions/components/available-functions.tsx, src/sandbox/components/views/deploy/deploy.tsx, src/sandbox/components/views/token-transfer.tsx
This is a quick fix to correctly pass the selected network to the stacks wallet for web extension.
fixes https://github.com/blockstack/explorer/issues/428
=> fix: correctly pass the network

src/components/footer.tsx
Fix: 462 - Added nofollow to footer.tsx to improve better SEO prospects.
=> fix: Added nofollow in footer.tsx

src/common/constants.ts
Use the following template to create your pull request
Fix missing VERSION in api call for all requests
For details refer to issue #451 
See issue #451
=> fix: version missing in api calls

src/components/meta-head.tsx, src/pages/sandbox/[...param].tsx
=> fix: Update hiro branding

next.config.js, package.json, sentry.client.config.js, sentry.server.config.js, yarn.lock
- update sentry to 6.17.2
- add query param to force send sentry transactions for testing
- remove unused DSN constant
=> fix: sentry updates

src/components/footer.tsx
=> fix: remove old footer links

src/components/transaction-item.tsx
=> feat: add nonce to transaction item

src/common/api/client.ts, src/common/state/network-slice.ts, src/common/state/store.ts, src/components/modals/modal-slice.ts, src/features/search/search-slice.ts, src/pages/_app.tsx, src/pages/address/[principal].tsx, src/pages/index.tsx, src/pages/txid/[txid].tsx, src/store/api-clients.ts
- remove default networks from persistent state
- fix naming inconsistencies
- fix RootState type
=> fix: network state naming and default networks persistence

src/common/state/store.ts, src/pages/_app.tsx
Fix network persistence subtree
=> fix: network persistence subtree

src/components/footer.tsx
=> feat: add new footer links

src/components/function-summary/value.tsx
=> fix: use principal hex value

src/components/tx/smart-contract.tsx
=> fix: pending contract deployment

src/components/function-summary/args.tsx
=> fix: filter null args

e2e/filters.spec.ts, e2e/mocks.ts, package.json, playwright.config.ts, sentry.client.config.js, sentry.server.config.js, src/common/hooks/use-filter-state.tsx, src/common/state/store.ts, src/components/filter-button.tsx, src/components/filter-panel.tsx, src/components/tabbed-transaction-list.tsx, src/components/transaction-list-item.tsx, src/components/transaction-list.tsx, src/features/transaction-list.tsx, src/features/transactions-filter/transactions-filter-slice.ts, src/pages/index.tsx, src/sandbox/components/transactions-panel.tsx, src/store/filter.ts, src/store/recoil/filter.ts, yarn.lock
- Refactor filters
- Configure playwright
- Add e2e test for filters
- Increase sentry sample size
closes #639 #568 #738
=> feat: refactor filters

src/components/transaction-details.tsx
tx page URLs don't carry query params
=> fix: tx page address urls

.github/workflows/ci.yml
- expose new out put in build job
- auto-approve deploy into stg based on new sem version
=> ci: auto-approve stg based on new sem ver

.github/workflows/lighthouse.yml
=> feat: add lighthouse to ci

package.json, playwright.config.ts, src/components/status.tsx, src/components/transaction-details.tsx, src/components/tx-events.tsx, src/features/blocks-visualizer/index.tsx, src/features/transaction/query-keys.ts, yarn.lock
(Experiment) Visualize last blocks on tx page
closes #758
=> feat: block visualizer

src/pages/_app.tsx
Disable refetching data on focus
=> fix: disable refetch on focus

src/components/code-block/code-block.tsx, src/features/address-page/address-summary.tsx, src/pages/address/[principal].tsx
- Wrap code lines
- Update nonce messaging
=> feat: tx page updates

src/components/filter-button.tsx, src/components/infinite-item-list.tsx, src/components/tabbed-transaction-list.tsx, src/features/account-transaction-list.tsx, src/features/transaction-list.tsx, src/features/transactions-filter/hooks/use-filter-scope.ts, src/features/transactions-filter/transactions-filter-slice.ts
Add filters to the homepage tx list
closes #355
=> feat: add filters to homepage tx list

.github/workflows/code-check.yml, package.json, src/common/hooks/use-token-metadata.ts, src/common/utils/string-utils.spec.ts, src/common/utils/string-utils.ts, src/common/utils/token-utils.spec.ts, src/common/utils/token-utils.ts, src/common/utils/url-utils.ts, src/common/validation/validate-url.ts, src/components/balances/token-asset-list-item.tsx, src/components/token-avatar.tsx, yarn.lock
This adds images to the fungible tokens
I also 
- added unit test and gh action for ci
- refactored metadata fetch to use useQuery and leverage some caching
=> feat: add fungible token images

src/components/btc-stx-price.tsx, src/components/footer.tsx, src/components/header.tsx
Add stx and btc prices to header
=> feat: add stx and btc prices to header

src/sandbox/components/screens/call-functions/components/available-functions.tsx
=> fix: read-only function call serialization error

src/common/api/client.ts, src/common/hooks/use-token-metadata.ts, src/common/utils/token-utils.ts, src/components/balances/token-asset-list-item.tsx, src/components/item-icon.tsx, src/components/token-avatar.tsx, src/components/transaction-item.tsx, src/features/account-transaction-list.tsx, src/features/transaction/query-keys.ts, src/features/transaction/use-transaction-queries.ts, src/modules/TransactionList/components/TxsList.tsx, src/modules/TransactionList/components/TxsListItem.tsx
Display tx transfers for addresses
=> feat: display tx transfers for addresses

src/sandbox/components/screens/call-functions/components/available-functions.tsx
=> feat: add principal validation to sandbox

README.md
Just adding some steps to the contribution guidelines
=> Improves the getting started guide

Dockerfile
thanks to @He1DAr 's upgrade, we can now reduce this container size down to ~176mb
=> reduce container size further

src/common/constants/network.ts, src/common/hooks/use-current-prices.ts, src/common/types/network.ts, src/components/loaders/skeleton-transaction.tsx, src/features/account-transaction-list.tsx, src/features/blocks-list/index.tsx, src/modules/TransactionList/hooks/useTransactionList.tsx, src/pages/_app.tsx, src/pages/address/[principal].tsx, src/pages/block/[hash].tsx, src/pages/microblock/[hash].tsx, src/pages/txid/[txid].tsx
=> feat: fetch txs and blocks on focus

src/common/constants.ts, src/features/transaction/use-transaction-queries.ts
=> fix: show maximums events for /txid

src/common/utils.tsx, src/components/btc-stx-block-links.tsx, src/components/links.tsx, src/features/blocks-list/block-list-item.tsx
fixes https://github.com/hirosystems/explorer/issues/880
=> fix: use semantic links for stx and btc block links

README.md, src/common/utils.tsx, src/features/search/use-search.ts
Closes https://github.com/hirosystems/explorer/issues/895
Enables search by block height.
=> feat: enable search by block height

src/common/constants.ts, src/common/types/search-results.ts, src/common/utils.tsx, src/components/balances/principal-token-balances.tsx, src/components/balances/token-asset-list-item.tsx, src/features/address/query-keys.ts, src/features/address/use-address-queries.ts, src/features/search/items/address-result-item.tsx, src/features/search/use-search.ts, src/pages/address/[principal].tsx
=> feat: display bns names

src/features/search/use-search.ts
=> fix: use first nft history

src/features/status-bar/status-bar.tsx
Hardcoded message for miners to upgrade to 2.05.0.5.1
=> feat: display hardcoded miner upgrade notification

src/features/status-bar/status-bar.tsx
Reverts hirosystems/explorer#904
=> Revert "feat: remove miners notification"

src/features/status-bar/status-bar.tsx
Reverts hirosystems/explorer#905
=> Revert "Revert "feat: remove miners notification""

package.json, src/components/transaction-details.tsx, src/components/tx-events.tsx, yarn.lock
- display clarity version for smart contract txs
- display alt recipient for coinbase txs
- display memo for STX transfer events
=> feat: stacks 2.1

src/components/timestamp.tsx
=> feat: copy timestamp

src/components/page.tsx
=> feat: display search bar on mobile

src/components/transaction-details.tsx
=> feat: exclude block info from txs in microblocks

README.md
=> fix: attempt to fix branch

src/middleware.ts, src/pages/_app.tsx
Reverts hirosystems/explorer#993
=> Revert "feat: remove middleware"

src/components/header.tsx, src/features/status-bar/status-bar.tsx, src/ui/TextLink.tsx
=> feat: stacks 2.1 banner

src/features/search/use-search.ts
=> fix: block search result missing data

src/app/PageWrapper.tsx
Updated banner text to reflect 2.1 activation and PoX instantiation
=> feat: 2.1 Activation banner

README.md, docs/getting-started.md, package.json, src/app/DefaultHeadTags.tsx, src/common/context/GlobalContext.tsx, src/components/meta-head.tsx
Updated URL to use Hiro domain.
=> Explorer domain migration

next.config.js, src/app/PageWrapper.tsx, src/app/txid/[txid]/TxPage.tsx
=> feat: subnets fast follows

src/app/PageWrapper.tsx, src/features/status-bar/status-bar.tsx, src/ui/ListItem.tsx, src/ui/UnorderedList.tsx
- Add new component `AlertBarBase`
- Add messaging for Stacks network update
=> feat: stacks network update alert

src/app/sandbox/components/ContractCall/DefaultView/PopularContracts.tsx
=> feat: add stacks 2.1 contracts

src/app/PageWrapper.tsx
Updates banner to version 2.3.0.0.1
=> fix: updates the version of stacks on the banner

src/common/utils/token-utils.spec.ts, src/common/utils/token-utils.ts, src/components/token-avatar.tsx
=> feat: display FT IPFS images

src/app/HomeClient.tsx, src/app/PageWrapper.tsx
=> feat: remove alert and display stats

src/app/sandbox/components/ContractCall/DefaultView/PopularContracts.tsx, src/app/sandbox/components/ContractCall/DefaultView/SearchContractsForm.tsx
This PR
* replaces pox-2 with pox-3 in the list of popular contracts
* replaces pox with pox-3 as the default contract
* fixes #1175
=> Replace pox-2 by pox-3

src/components/filter-button.tsx, src/components/filter-panel.tsx
Closes #1167  Modal Overflow Issue When Clicking Filter Button on Transaction Page 
Details: Added left margin and corrected box shadow value
Before 
After
=> fix: filter modal overflow and modal shadow 

docs/overview.md
Updated H1 to use the product name.
=> fix: Update title for overview

src/common/constants.ts, src/components/add-network-form.tsx
Closes https://github.com/hirosystems/explorer/issues/1171
=> feat: skip network id check for subnets

src/features/status-bar/status-bar.tsx
This pr solves #1189 
closes #1189
=> fix: add underline to the link in alert

.github/workflows/code-check.yml, .gitignore, package.json, pnpm-lock.yaml
Upload code coverage report to Codecov
=> feat: codecov integration

README.md
Display environment status for prod, stg, and dev.
=> fix: readme environment badges

CHANGELOG.md, src/app/token/[tokenId]/page.tsx, src/pages/index.tsx, src/pages/token/[tokenId].tsx
* add redis url to next config ([3c3ca8a](https://github.com/hirosystems/explorer/commit/3c3ca8a4f868531b90ade10ff16b3f6474fc60c7))
=> chore(release): 1.112.1

src/app/tokens/TokensList/TokensList.tsx
=> fix: change search input type on token list

src/common/constants.ts
=> fix: swap network ids

src/app/components/BlockList/index.tsx
=> fix: load more blocks

package.json, pnpm-lock.yaml, src/app/token/[tokenId]/getTokenInfo.ts, src/app/txid/[txId]/Alert.tsx, src/common/utils/cache-client.ts
Add [sharp](https://www.npmjs.com/package/sharp) for next.js image processing.
=> feat: add sharp for image processing

src/app/_components/BlockList/__tests__/BlocksListBase.test.tsx, src/app/_components/BlockList/index.tsx
=> fix: refresh block view when switching live view on

src/app/address/[principal]/AddressSummary.tsx, src/app/txid/[txId]/CoinbasePage/TxDetails.tsx, src/app/txid/[txId]/ContractCall/TxDetails.tsx, src/app/txid/[txId]/PoisonMicroblock/TxDetails.tsx, src/app/txid/[txId]/SmartContract/TxDetails.tsx, src/app/txid/[txId]/TenureChange/TxDetails.tsx, src/app/txid/[txId]/TokenTransfer/TxDetails.tsx, src/app/txid/[txId]/TxDetails/Amount.tsx, src/app/txid/[txId]/TxDetails/Fees.tsx, src/common/components/KeyValueHorizontal.tsx
=> fix: tx and address page summary mobile style

src/app/txid/[txId]/Events.tsx, src/app/txid/[txId]/TxDetails/BlockHeight.tsx
=> fix: events style mobile

src/common/constants/contracts/hello-world-contract.tsx
=> fix: hello world contract

src/app/_components/BlockList/LayoutA/__tests__/__snapshots__/BlockListWithControls.test.tsx.snap, src/features/txs-list/ListItem/TxListItem.tsx, src/features/txs-list/tabs/TxListTabsBase.tsx
Resolves https://github.com/hirosystems/explorer/issues/1365
=> feat(nonce): added nonce info to address page

src/app/_components/BlockList/LayoutA/__tests__/BlockListWithControls.test.tsx, src/app/_components/BlockList/LayoutA/__tests__/__snapshots__/BlockListWithControls.test.tsx.snap, src/app/_components/PageWrapper.tsx, src/app/_components/StatusBar/StatusBarBase.tsx, src/app/_components/StatusBar/__tests__/StatusBar.test.ts, src/app/_components/StatusBar/__tests__/__snapshots__/StatusBarBase.test.tsx.snap, src/app/_components/StatusBar/utils.ts
=> feat: Nakamoto voting banner

src/__tests__/pages/token/[tokenId].test.tsx, src/app/_components/BlockList/LayoutA/__tests__/__snapshots__/BlockListWithControls.test.tsx.snap, src/app/_components/BlockList/index.tsx, src/app/_components/Footer.tsx, src/app/address/[principal]/StxBalance/BalanceItem.tsx, src/app/block/[hash]/tx-lists/BlockTxsList.tsx, src/app/getTokenPriceInfo.ts, src/app/stxPrice/route.ts, src/app/token/[tokenId]/PageClient.tsx, src/app/token/[tokenId]/TokenInfo/Price.tsx, src/app/token/[tokenId]/TokenInfo/Transaction.tsx, src/app/token/[tokenId]/TokenInfo/index.tsx, src/app/token/[tokenId]/getTokenInfo.ts, src/app/token/[tokenId]/types.ts, src/app/txid/[txId]/TxDetails/ContractName.tsx, src/common/components/FilterMenu.tsx, src/common/components/Section.tsx, src/common/components/StxPriceButton/useStxPriceForTx.ts, src/common/constants/env.ts, src/common/queries/useCurrentPrices.ts, src/common/types/lunarCrush.ts
=> feat: replace CoinGecko with LunarCrush

src/features/txs-list/ListItem/MempoolTxListItem.tsx
- fixes typo (not sure if spelling was intentional)
=> chore: fix typo

src/features/txs-list/TxTitle.tsx
Addresses https://github.com/hirosystems/explorer/issues/1473
=> fix(coinbase-tx-item): removed coinbase from tx title

src/app/PageClient.tsx, src/features/txs-list/TxTitle.tsx, src/features/txs-list/tabs/TxListTabs.tsx, src/features/txs-list/tabs/TxListTabsBase.tsx
Addresses https://github.com/hirosystems/explorer/issues/1476
=> feat(remove-filter-from-txs-on-homepage): done

src/app/_components/NavBar/MobileNav.tsx, src/app/_components/NavBar/NetworkModeBanner.tsx, src/app/_components/NavBar/__tests__/MobileNav.test.tsx, src/app/_components/NavBar/index.tsx, src/app/_components/StatusBar/IncidentsStatusBar.tsx, src/app/_components/StatusBar/status-bar-slice.ts, src/common/state/store.ts, src/common/utils/test-utils/renderWithReduxProvider.tsx
Addresses https://github.com/hirosystems/explorer/issues/1432
=> fix: mobile banner

src/app/_components/Footer.tsx, src/app/transactions/MempoolFeePieChart.tsx
Addresses https://github.com/hirosystems/explorer/issues/1544
=> feat(change-support-links): changed href and link text

Dockerfile, package.json, pnpm-lock.yaml, src/app/_components/BlockList/LayoutA/__tests__/__snapshots__/BlockListWithControls.test.tsx.snap, src/app/_components/Footer.tsx, src/app/support/PageClient.tsx, src/app/support/page.tsx, src/app/support/skeleton.tsx
=> feat: support page

src/app/_components/Stats/CurrentStackingCycle/index.tsx, src/app/_components/Stats/NextStackingCycle/index.tsx
=> feat: home stats error UI

src/app/_components/PageWrapper.tsx
=> feat: release banner

src/app/_components/PageWrapper.tsx
=> feat: release banner fast follow

src/app/_components/PageWrapper.tsx
fix: 2.5.0.0.3 New Release banner
=> fix: 2.5.0.0.3 New Release banner

src/app/_components/PageWrapper.tsx
Updated 2.5 Instantiation banner
=> fix: Updated Banner with Mainnet instantiation

src/app/_components/StatusBar/IncidentsStatusBar.tsx
- Only show status bar on testnet if it includes `Testnet Update:`
- Fix layout issue
=> feat: status bar updates

src/app/_components/NavBar/BtcStxPrice.tsx, src/app/_components/NavBar/__tests__/__snapshots__/MobileNav.test.tsx.snap
=> fix(price-text): fixed color of price txt

src/app/_components/BlockList/BlockCount.tsx, src/app/_components/BlockList/Grouped/BlockListGrouped.tsx, src/app/_components/BlockList/Ungrouped/BlockListUngrouped.tsx
Removes the link styling for links on the first btc block in the blocklist
=> fix(blocklist-links): removed link styling 4 1st btc blk

src/common/components/modals/Nakamoto.tsx
=> feat: disable nakamoto modal

src/app/_components/BlockList/SkeletonBlockList.tsx, src/app/page.tsx, src/app/skeleton.tsx, src/common/components/TwoColumnsListItem.tsx, src/common/components/TwoColumnsListItemSkeleton.tsx, src/features/txs-list/SkeletonTxsList.tsx
fixed homepage loading where the skeletons weren't showing up
=> fix(homepage-loading): fixed homepage loading

src/common/context/GlobalContext.tsx, src/common/context/__tests__/GlobalContext.test.tsx
=> feat: add testnet archive network

src/app/_components/NavBar/NetworkLabel.tsx, src/app/_components/PageWrapper.tsx
- Add status bar
- Update network tags
=> feat: UI updates

src/app/txid/[txId]/Events.tsx
closes https://github.com/hirosystems/explorer/issues/1451
=> fix: remove tx events duplicate

src/app/_components/PageWrapper.tsx, src/app/_components/StatusBar/CMSStatusBars.tsx, src/app/getStatusBarContent.ts, src/app/signers/SignersMapComponent.tsx, src/app/signers/useSignerLocations.ts
Issue: https://hiropbc.slack.com/archives/C03TU42NL05/p1719424866586789
=> fix(maps-testnet): showing custom error message

src/features/search/items/block-result-item.tsx
=> fix: tx count in block search result

src/features/txs-list/TxTitle.tsx
closes https://github.com/hirosystems/explorer/issues/1702
=> chore: redeisgn for function call tx ui

src/app/_components/NavBar/DesktopNav.tsx, src/app/_components/NavBar/LabelWrapper.tsx, src/app/_components/NavBar/NetworkLabel.tsx, src/app/_components/NavBar/__tests__/__snapshots__/DesktopNav.test.tsx.snap
closes [#1562](https://github.com/hirosystems/explorer/issues/1562)
=> fix: devnet text overflow

src/common/queries/useSearchQuery.ts
closes [#1078](https://github.com/hirosystems/explorer/issues/1078)
=> fix: added search exception in case an addr is not found

src/app/signers/SignerDistributionLegend.tsx, src/app/signers/SignersHeader.tsx, src/app/signers/consts.ts
=> feat: add kiln as a signer

src/app/_components/Stats/StxSupply/index.tsx
=> feat: update supply information

src/app/_components/NavBar/DesktopNav.tsx, src/app/_components/NavBar/__tests__/__snapshots__/DesktopNav.test.tsx.snap, src/app/signers/SignersMap.tsx, src/app/signers/consts.ts
closes https://github.com/hirosystems/explorer/issues/1735
=> feat: added figment signer

src/app/_components/NavBar/DesktopNav.tsx, src/app/_components/NavBar/__tests__/__snapshots__/DesktopNav.test.tsx.snap, src/app/_components/PageWrapper.tsx, src/app/_components/StatusBar/NonHiroNetworkWarningBar.tsx, src/app/_components/StatusBar/__tests__/isHiroSubdomain.test.ts
=> feat: warning bar for non Hiro networks

src/app/sandbox/components/Argument/PrimitiveArgumentInput.tsx, src/app/sandbox/components/Argument/TupleArgumentInput.tsx, src/app/sandbox/components/ContractCall/FunctionView.tsx, src/app/sandbox/components/ContractCall/PostConditionForm.tsx, src/app/sandbox/components/ContractCall/__tests__/PostConditionForm.test.ts, src/app/sandbox/transfer/PageClient.tsx, src/app/sandbox/utils.ts, src/app/token/[tokenId]/PageClient.tsx, src/common/utils/number-utils.ts, src/ui/theme/componentTheme/Menu.ts
Reintroduces post conditions
Original PR: https://github.com/hirosystems/explorer/pull/974
Revert PR: https://github.com/hirosystems/explorer/pull/979
Reasons for revert:
https://hiropbc.slack.com/archives/C03TU42NL05/p1674856003091539
Reasons for altering the design:
https://hiropbc.slack.com/archives/C03TU42NL05/p1724101464300599
Instructions for creating your own FT PC:
Visit the mock-usdc token page, or whatever page of a token that you have some amount of.
http://localhost:3000/txid/ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mock-usdc?chain=testnet
Go to the transfer function.
Enter required input.
Manual Tests:
FT transfer with no PC:
https://explorer.hiro.so/txid/06fcf31adfa8b589b220f5464413ee1adf6209fa8836683e7434d713143d45bd?chain=testnet
FT transfer failed with PC: …
=> feat: added post conditions

src/app/search/PageClient.tsx, src/app/search/TxSearchResult.tsx, src/app/search/filters/Address.tsx, src/app/search/filters/After.tsx, src/app/search/filters/Before.tsx, src/app/search/filters/Date.tsx, src/app/search/filters/DateRange.tsx, src/app/search/page.tsx, src/app/token/[tokenId]/getTokenInfo.ts, src/common/context/__tests__/GlobalContext.test.tsx, src/common/queries/__tests__/useSearchQuery.ts, src/common/queries/useConfirmedTransactionsInfinite.ts, src/common/queries/useSearchQuery.ts, src/features/search/NoTxs.tsx, src/features/search/Search.tsx, src/features/search/dropdown/search-results-card.tsx, src/features/search/search-field/search-box.tsx, src/features/search/search-field/search-input.tsx
- Sync  search bar with filters
- Redirect to entity page (tx, address, etc.) if there's a single search result.
closes #1766 #1750 #1755
=> feat: sync search bar with filters

src/app/address/[principal]/TokenBalanceCard/FtBalance.tsx, src/app/address/[principal]/TokenBalanceCard/NftBalance.tsx, src/common/components/TwoColumnsListItem.tsx
Add client side pagination with lazy loading to avoid hitting rate limit.
Closes #1782
=> feat: holdings client side pagination

src/features/search/dropdown/search-results-card.tsx
=> fix: search tx url

.gitignore, src/common/constants/env.ts
Resolves https://github.com/hirosystems/explorer/issues/1772 and https://github.com/hirosystems/explorer/issues/1777
=> feat: use regtest btc explorer for testnet

.eslintrc.js, .github/workflows/ci.yml, .gitignore, Dockerfile, next.config.js, package.json, pnpm-lock.yaml, sentry.client.config.ts, src/app/PageClient.tsx, src/app/_components/Providers.tsx, src/app/global-error.tsx, src/app/instrumentation.ts, src/app/sandbox/transfer/PageClient.tsx, src/common/constants/env.ts, src/common/queries/usePoxInforRaw.ts, src/common/utils/error-utils.ts, src/common/utils/fetchWithApiKey.ts, tsconfig.json
Proof that errors are logging in dev with sourcemaps - https://hirosystems.sentry.io/issues/5801423335/?environment=development&project=4507788896239616&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=0
=> feat: added sentry

src/app/_components/BlockList/BlocksPage/BlocksPageHeaders.tsx, src/common/components/RelativeTimeDisplay.tsx, src/common/queries/useBurnBlocksInfinite.ts
=> feat: blocks page improvements

src/features/search/items/address-result-item.tsx, src/features/search/items/block-result-item.tsx, src/features/search/items/tx-list-result-item.tsx, src/features/search/items/tx-result-item.tsx
=> feat: add class name to search result

src/app/_components/BlockList/Controls.tsx, src/app/_components/BlockList/LayoutA/__tests__/__snapshots__/BlockListWithControls.test.tsx.snap, src/common/components/StxPrice.tsx, src/common/components/StxPriceButton/index.tsx
- hide live view
- only display stx price on mainnet
=> fix: 3.0 fast follows

.eslintrc.js, .github/workflows/deploy-storybook-github-pages.yaml, .gitignore, .storybook/main.ts, .storybook/preview.tsx, package.json, pnpm-lock.yaml, src/stories/Button.stories.ts
=> feat: setup storybook

.github/workflows/deploy-storybook-github-pages.yaml
Install pnpm in workflow before using it
=> fix: storybook workflow

README.md
=> feat: redeploy

src/stories/Breakpoints.stories.tsx, src/ui/theme/theme.ts
Adds new design system breakpoint values to the theme so that they can be referenced in the code
```
import { Box, useBreakpointValue } from '@chakra-ui/react';
const MyComponent = () => {
// Using semantic tokens to determine different logic based on breakpoint
const boxColor = useBreakpointValue({
base: 'gray.100',
smallScreen: 'blue.200',
mediumScreen: 'green.300',
largeScreen: 'orange.400'
});
return (
<Box
width={{ base: '100%', md: '50%' }}
bg={boxColor}
padding="1rem"
>
Responsive Box with Semantic Token Colors
</Box>
);
};
export default MyComponent;
```
Breakpoints in theme.breakpoints: The box will use responsive widths.
Breakpoints in semanticTokens: The background color will change based on the semantic tokens for the breakpoints. …
=> feat: added breakpoints into our theme

src/stories/Elevation.stories.tsx, src/ui/theme/theme.ts
Added elevation to theme for redesign
#1845
=> feat: added elevation to redesign

src/app/block/[hash]/PageClient.tsx
Removing test code that was accidently introduced
=> fix: removed test code

src/app/sandbox/deploy/LeftSection.tsx
Adding some text clarifying that deploy currently doesn't support Clarity 3 deployments
Also fixes some icon sizes
https://github.com/hirosystems/explorer/issues/1855#issuecomment-2429192330
=> feat: added deploy note text about clarinet

src/ui/theme/theme.ts
Fixing a bad rebase that put some theme variables under semantic tokens
=> fix: fixed theme bug where theme was in semantic tokens

src/stories/BorderRadius.stories.tsx, src/ui/theme/theme.ts
Added border radius to theme for redesign
#1844
=> feat: added border radius for redesign

package.json, pnpm-lock.yaml
=> feat: upgrade nextjs

next.config.js
=> feat: explocot disable dangerouslyallowsvg

next.config.js
=> feat: remove img remote pattern

src/common/components/modals/AddNetwork/utils.ts
=> feat: allow custom network id

src/common/utils/transactions.ts
Display dropped label for all dropped tx statuses.
closes #1907
=> feat: display dropped label for all dropped tx statuses

src/app/txid/[txId]/TxAlerts.tsx
=> feat: remove nakamoto modal

src/app/signers/consts.ts
Add Nansen to signers key map
closes #1934
=> feat: add Nansen to signers key map

.eslintrc.js, src/app/address/[principal]/StxBalance/BalanceItem.tsx, src/app/signers/consts.ts, src/common/components/StxPriceButton/useStxPriceForTx.ts, src/common/queries/useCurrentPrices.ts
=> fix: remove stxprice suspense

src/__tests__/pages/token/[tokenId].test.tsx, src/app/_components/PageTitle.tsx, src/app/_components/PageWrapper.tsx, src/app/_components/Stats/StackingCycle.tsx, src/app/_components/Stats/StxSupply/index.tsx, src/app/signer/[signerKey]/PageClient.tsx, src/app/signer/[signerKey]/StackingHistoryTable.tsx, src/app/signers/StxStackedCard.tsx, src/app/signers/TotalStackedCard.tsx, src/app/token/[tokenId]/PageClient.tsx, src/app/token/[tokenId]/Tabs/holders/Holders.tsx, src/app/token/[tokenId]/TokenInfo/MarketCap.tsx, src/app/token/[tokenId]/TokenInfo/Supply.tsx, src/app/token/[tokenId]/TokenInfo/Transaction.tsx, src/app/token/[tokenId]/TokenInfo/index.tsx, src/app/token/[tokenId]/getTokenInfo.ts, src/app/token/[tokenId]/types.ts, src/app/tokens/TokenRow/index.tsx, src/app/tokens/TokensList/TokenTable.tsx, src/app/tokens/__tests__/__snapshots__/TokenRow.test.tsx.snap, src/app/tokens/utils.ts, src/common/queries/useFeeTransfer.ts, src/common/utils/__tests__/utils.spec.ts, src/common/utils/utils.ts, src/ui/theme/space.ts
Slack context - https://hiropbc.slack.com/archives/C03TU42NL05/p1734370346313639
Added sbtc specific UI changes - https://www.figma.com/design/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=10031-38309&m=dev
Added token image to each tokenid page
Fixed holder balances not accounting for token decimals
Fixed token list total supply figure not accounting for token decimals
Fixed number abbreviation function
Wrote tests for it
https://github.com/hirosystems/explorer/issues/1937
=> fix: sbtc page

src/app/token/[tokenId]/PageClient.tsx, src/app/token/[tokenId]/TokenInfo/Price.tsx, src/app/token/[tokenId]/TokenInfo/TrendArrow.tsx, src/app/token/[tokenId]/TokenInfo/index.tsx, src/app/token/[tokenId]/page.tsx, src/common/context/GlobalContextProvider.tsx, src/common/context/__tests__/GlobalContext.test.tsx
Removing deprecated naka testnet
=> feat: remove naka testnet

src/app/sandbox/faucet/PageClient.tsx, src/common/queries/useFaucet.ts
=> fix: faucet request fixed

src/app/tokens/TokensList/TokenTableSkeleton.tsx, src/app/tokens/useTokens.ts
Moves sBTC to the top of the token list
https://github.com/hirosystems/explorer/issues/1940
=> feat: added sbtc to top of tokens list

src/common/components/transaction-item.tsx
Fixed regression with pending tx's receipt time showing as undefined
https://github.com/hirosystems/explorer/issues/1925
=> fix: fixed pending tx receipt time

src/common/components/modals/SBTCModal.tsx
- [] Refactor
Changing the sbtc link and text
Slack context
=> fix: changed the link and text

src/app/token/[tokenId]/TokenInfo/index.tsx
Setting sbtc marketcap rank to n/a
slack context - https://hiropbc.slack.com/archives/C03TU42NL05/p1734726529185749?thread_ts=1734726369.188419&cid=C03TU42NL05
=> fix: set sbtc marketcap rank to n/a

src/app/_components/PageWrapper.tsx
=> feat: removed the sbtc modal

src/app/token/[tokenId]/PageClient.tsx
Display a banner for risky tokens
=> feat: risky tokens banner

src/app/_components/NavBar/NetworkLabel.tsx, src/app/txid/[txId]/TxAlerts.tsx, src/app/txid/[txId]/TxPage.tsx
Updating the text around tx states
https://github.com/hirosystems/explorer/issues/1408
https://github.com/hirosystems/explorer/issues/1954
=> feat: update tx state text

src/ui/theme/semanticTokens.ts
=> feat: added new semantic tokens

src/app/_components/NewNavBar/NavBar.tsx, src/app/_components/Search/ResultItem.tsx, src/app/_components/Search/Search.tsx, src/app/_components/Search/SearchLink.tsx, src/common/queries/__tests__/useSearchQuery.ts, src/common/queries/useSearchQuery.ts, src/common/types/search-results.ts, src/features/search/dropdown/search-results-card.tsx, src/features/search/items/search-result-item.tsx, src/features/search/search-field/search-input.tsx, src/features/search/search-slice.ts
=> feat: redesign - add search to nav

src/app/_components/StatusBar/IncidentsStatusBar.tsx
Fix status bar styling when no incidents
=> fix: status bar styling

src/app/sandbox/components/ContractCall/DefaultView/SearchContractsForm.tsx, src/app/sandbox/components/ContractCall/DefaultView/index.tsx, src/app/sandbox/contract-call/[[...params]]/PageClient.tsx
- Fix header font size
- Add error message if contract not found
=> fix: sandbox header font size and add error message

src/app/_components/PageTitle.tsx
=> fix: page title font

src/app/signers/CurrentCycleCard.tsx, src/app/signers/SignerDistributionPieChart.tsx, src/app/signers/skeleton.tsx
Fixed some signers page ui bugs:
- Signer distribution piechart skeleton was too big
- The size of the container for the current cycle pie chart was too big
=> fix: fixed some signers page ui bugs

src/app/token/[tokenId]/PageClient.tsx
Labels DROID token as scam
https://github.com/hirosystems/explorer/issues/2020
=> feat: added droid token to scams

src/app/token/[tokenId]/PageClient.tsx
Reverts hirosystems/explorer#2022
=> Revert "feat: added droid token to scams"

src/app/token/[tokenId]/PageClient.tsx, src/app/tokens/TokenRow/index.tsx
Listing this DROID token as verified
=> fix: listed droid as verified token

src/app/_components/BlockList/Sockets/use-stacks-api-socket-client.ts, src/app/_components/RecentBlocks/BtcBlock.tsx, src/app/_components/RecentBlocks/FadingOverlay.tsx, src/app/_components/RecentBlocks/NewBlockPlaceholder.tsx, src/app/_components/RecentBlocks/RecentBlocks.tsx, src/app/_components/RecentBlocks/RecentBtcBlocks.tsx, src/app/_components/RecentBlocks/RecentStxBlocks.tsx, src/app/_components/RecentBlocks/StxBlock.tsx, src/app/_components/RecentBlocks/__tests__/formatTimestamp.test.ts, src/app/_components/RecentBlocks/consts.ts, src/app/_components/RecentBlocks/utils.ts, src/common/queries/useBlockListInfinite.ts, src/ui/theme/colors.ts
- Add recent STX blocks tab
- Improve accessibility for BTC recent blocks
closes #2038
=> feat: redesign - homepage - recent-blocks: stx

src/app/signers/data/UseSigner.ts
The issue with the mapping was it was done after we had removed null values from the array, so the cycle array no longer corresponded to the response array
https://github.com/hirosystems/explorer/issues/2048
=> fix: fixed the signer cycle mapping bug

package.json, pnpm-lock.yaml
=> fix: pnpm-lock

.github/workflows/code-check.yml, .github/workflows/deploy-storybook-github-pages.yaml, .github/workflows/linting.yml, Dockerfile, pnpm-lock.yaml, src/api/callApiWithErrorHandling.ts, src/app/PageClient.tsx, src/app/_components/PageWrapper.tsx, src/app/_components/RecentBlocks/NewBlockPlaceholder.tsx, src/app/_components/RecentBlocks/RecentBlocks.tsx, src/app/_components/RecentBlocks/RecentBtcBlocks.tsx, src/app/_components/RecentBlocks/RecentStxBlocks.tsx, src/app/_components/RecentBlocks/StxBlock.tsx, src/app/_components/RecentBlocks/consts.ts, src/app/home-redesign/context.tsx, src/app/home-redesign/data.ts, src/app/home-redesign/page.tsx, src/app/transactions/PageClient.tsx, src/common/components/table/table-examples/BlocksTable.tsx, src/common/date-utils.ts, src/common/queries/useBlockListInfinite.ts, src/common/queries/useBurnBlocksInfinite.ts, src/common/queries/useSearchQuery.ts, src/common/utils/url-utils.ts
- Creating new home-redesign page
- Implement SSR for `RecentBlocks` section
- Fix prettier version on CI
#2072
=> feat: Homepage - SSR- Recent blocks

.github/workflows/ci.yml, .github/workflows/deploy.yml
=> ci: update auth for deploys

src/app/_components/NetworkOverview/NetworkOverview.tsx, src/app/_components/NetworkOverview/NetworkOverviewContextProvider.tsx, src/app/_components/NetworkOverview/SectionHeader.tsx, src/app/_components/PageWrapper.tsx, src/app/_components/RecentBlocks/RecentBlocks.tsx, src/app/_components/StackingSection/StackingSection.tsx, src/app/home-redesign/context.tsx, src/app/home-redesign/data.ts, src/app/home-redesign/page.tsx, src/common/date-utils.ts, src/common/utils/__tests__/date-utils.test.ts, src/common/utils/__tests__/network-utils.test.ts, src/common/utils/__tests__/utils.spec.ts, src/common/utils/date-utils.ts, src/common/utils/network-utils.ts, src/common/utils/utils.ts
Implement SSR data fetching for stacking and network overview section.
closes #2077 #2076
=> feat: homepage - ssr - stacking and network overview section

src/common/utils/__tests__/utils.test.tsx, src/common/utils/utils.ts
- Handling zero in formatNumber
=> fix: handling zero in formatNumber

src/app/_components/NewNavBar/FeePopover.tsx, src/app/_components/NewNavBar/SettingsPopover.tsx, src/common/components/TabPopover.tsx
Refactored settings and fee popovers to use the tab popover design component
=> feat: refactored code to use tabpopover

src/app/_components/NewNavBar/FeePopover.tsx
Fixed the tab scroll in the fee popover
https://github.com/hirosystems/explorer/issues/2067
=> feat: fixed the scroll

pnpm-lock.yaml, src/app/_components/NewNavBar/NavBar.tsx, src/app/_components/NewNavBar/PagesSlidingMenu.tsx, src/app/transactions/page.tsx, src/common/components/SlidingMenu.tsx, src/common/components/table/table-examples/TxTableCellRenderers.tsx, src/common/components/table/table-examples/TxsTable.tsx, src/common/queries/useConfirmedTransactionsInfinite.ts, src/common/queries/useSearchQuery.ts, src/stories/SlidingMenu.stories.tsx
fixes the hydration mismatch and caching issues to improve gtmetrix performance
Also fixes the sliding menu implementation to make it ssr-able
https://github.com/hirosystems/explorer/issues/2066
- [ X I have tested the change on desktop and mobile.
=> Fix table hydration issues

src/common/utils/__tests__/utils.test.tsx
=> fix: main tests

src/app/tokens/TokensList/TokenTable.tsx, src/common/queries/useFtTokens.ts
=> fix: fixed token list

src/app/_components/BlockList/Ungrouped/BlockListUngrouped.tsx
Fixes btc icon size issue
closes https://github.com/hirosystems/explorer/issues/2129
=> fix: fixed btc icon size

src/app/txid/[txId]/TxPage.tsx
Fixes tx id badges colors
closes https://github.com/hirosystems/explorer/issues/2146
=> fix: fixed tx badges

src/ui/theme/colors.ts
Swaps old purple stacks colors for new orange stacks colors 
closes https://github.com/hirosystems/explorer/issues/2140
=> fix: swapped colors

src/app/_components/RecentBlocks/RecentBlocks.tsx
Fix new block UI disappearing on tab toggle
closes #2130
=> fix: new block UI disappearing on tab toggle

src/app/_components/BlockList/BlockListItem.tsx, src/app/_components/BlockList/Grouped/BlockListGrouped.tsx, src/app/search/filters/index.tsx, src/app/tokens/__tests__/__snapshots__/TokenRow.test.tsx.snap, src/common/components/BtcStxBlockLinks.tsx, src/ui/theme/colors.ts
Replaces old stacks icon with the new one. However, this color issue is resolved by this PR  https://github.com/hirosystems/explorer/pull/2182
closes https://github.com/hirosystems/explorer/issues/2147
=> fix: updates stacks icons

src/app/_components/NetworkOverview/NetworkOverview.tsx
- Display last 6 hours of data
- Display time span indicator
- Responsive / even xAxis ticks
closes #2130
=> feat: network chart fast follows

src/app/_components/Search/DoubleGradientBorderWrapper.tsx, src/app/_components/Search/Search.tsx
- Add close button to search bar on mobile
- Remove hiding search UI on input blur
closes #2185
=> feat: search UX improvements

src/app/_components/Search/Search.tsx
=> fix: handle contract search

src/common/constants/meta.ts
- Update OG description
closes #2196
=> feat: update og description

src/app/_components/Search/ResultItem.tsx, src/app/_components/Search/Search.tsx
- Navigate to search result on enter
closes #2198
=> feat: navigate to search result on enter

src/app/_components/NewNavBar/MobileNavPage.tsx
-Fix mobile menu settings overlapping
closes #2236
=> fix: mobile menu settings overlapping

src/app/_components/MempoolSection/TxCountChart.tsx, src/app/_components/MempoolSection/index.tsx
Update mempool chart
closes #2220
=> feat: update mempool chart

src/app/_components/NetworkOverview/ChartTooltip.tsx, src/app/_components/NetworkOverview/NetworkOverview.tsx, src/app/_components/RecentBlocks/BtcBlock.tsx, src/app/_components/RecentBlocks/StxBlock.tsx, src/common/utils/__tests__/time-utils.test.ts, src/common/utils/time-utils.ts
Fixes hydration issue related to chart timestamp
Also fixes the chart tooltip to differentiate between txs and blocks
=> fix: fixed hydration issue related to timestamp

.github/workflows/ci.yml
Add GPG secrets for signed bot commits
=> ci: add gpg keys for signed commits

src/app/_components/NewNavBar/PagesLinks.tsx
If the network is testnet, the sandbox link links back to mainnet.
This PR fixes this network issue.
=> fix: fixed sandbox link

src/app/sandbox/components/ContractCall/ReadOnlyField.tsx, src/common/queries/useCallReadOnlyFunction.ts
I fixed the function call cache issue
Fixes https://github.com/hirosystems/explorer/issues/2320
=> fix: fixed function call cache issue

src/app/_components/TxsSection.tsx, src/common/components/table/table-examples/TxsTable.tsx
Adds a tooltip to the timestamp col in the txs table
https://github.com/hirosystems/explorer/issues/2208
=> feat: added tooltip tp timestamp col

src/app/_components/RecentBlocks/BtcBlock.tsx, src/app/_components/RecentBlocks/RecentBlocks.tsx, src/app/_components/RecentBlocks/StxBlock.tsx, src/app/_components/StackingSection/StackingSection.tsx, src/ui/icons/StacksIconBlock.tsx
Fixes stacks icons
closes https://github.com/hirosystems/explorer/issues/2033
=> fix: fixed stacks icons

src/common/components/table/table-examples/TxsTable.tsx
Removed to col from coinbase txs in txs table
closes https://github.com/hirosystems/explorer/issues/2287
=> feat: removed to col from coinbase txs

src/app/_components/Search/Search.tsx
Changed the search placeholder text to add clarity
closes https://github.com/hirosystems/explorer/issues/2217
=> chore: changed the search placeholder to add clarity

src/common/components/table/TableScrollIndicatorWrapper.tsx
Adds a scroll right functionality to the scroll indicator
closes https://github.com/hirosystems/explorer/issues/2273
=> feat: added a scroll right functionality to the scroll indicator

src/ui/theme/fonts.ts
Updates fall back fonts from old design system to new design system. Some components where still fetching the old fonts
=> fix: remove legacy design font styles

src/app/_components/StackingSection/StackingSection.tsx
Increased the area of the progresss bar tooltip
closes https://github.com/hirosystems/explorer/issues/2228
=> chore: increases the area of the progress bar tooltip

src/app/_components/FeeSection/index.tsx, src/app/_components/MempoolSection/index.tsx, src/app/_components/NetworkOverview/NetworkOverview.tsx, src/app/_components/RecentBlocks/RecentBtcBlocks.tsx, src/app/_components/RecentBlocks/RecentStxBlocks.tsx, src/app/_components/SSRDisabledMessage.tsx, src/app/_components/StackingSection/StackingSection.tsx, src/app/context.tsx, src/app/page.tsx
Disable SSR query param. This would allow Devnet to work with latest version of Explorer.
closes: #2312
=> feat: disable SSR query param

instrumentation.ts
=> feat: update sentry config

src/app/getStatusBarContent.ts
=> feat: increase CMS revalidate time

src/app/_components/RecentBlocks/StxBlock.tsx
Stx blocks in recent blocks are showing burn block time not block time
=> fix: fixed the stx block times in recent blocks

src/app/_components/NewNavBar/MobileNavPage.tsx, src/app/_components/NewNavBar/NavBar.tsx, src/app/_components/NewNavBar/Prices.tsx, src/app/_components/PageWrapper.tsx, src/app/_components/Providers.tsx, src/app/layout.tsx, src/common/context/GlobalContextProvider.tsx, src/common/queries/useCurrentPrices.ts
=> feat: disable historical price

src/app/_components/StatusBar/NonHiroNetworkWarningBar.tsx, src/app/_components/StatusBar/__tests__/isHiroSubdomain.test.ts, src/common/constants/env.ts, src/common/context/GlobalContextProvider.tsx, src/common/context/__tests__/GlobalContext.test.tsx, src/common/hooks/__tests__/useDevnetRedirect.test.ts, src/common/hooks/useDevnetRedirect.ts, src/common/utils/__tests__/network-utils.test.ts, src/common/utils/buildUrl.ts, src/common/utils/network-utils.ts
- Add ssr=false query param for devnet
- Improve devnet DX by auto setting query params
- Create dedicated banner text for devnet
- Fix banner styling
closes #2312
=> feat: devnet improvements

src/instrumentation-client.ts
Some of the 3rd party extension errors are making their way to Sentry and causing noise / consume quota.
=> fix: sentry: filter out 3rd party extension errors

src/app/txid/[txId]/page.tsx
=> fix: tx page query params

README.md
=> fix: redeploy

src/app/txid/[txId]/PageClient.tsx
Releasing the nex tx id pages for token transfer, coinbase, and tenure change
=> feat: removed the tx id feature flag checks

src/app/mempool/data.ts, src/app/mempool/page.tsx, src/common/components/table/mempool-table/MempoolTableWithFilters.tsx, src/common/components/table/table-examples/MempoolTable.tsx, src/common/queries/useMempoolTransactionsInfinite.ts
=> feat: mempool page pagination

src/app/_components/FeeSection/index.tsx, src/app/_components/MempoolSection/index.tsx, src/app/mempool/page.tsx, src/app/page.tsx, src/common/components/table/table-examples/MempoolTable.tsx, src/common/queries/useFeeEstimates.ts
- allow mempool stats and fee estimate sections to work when ssr is disabled
- reload mempool stats and fee estimate data when updating mempool table
closes #2307
=> feat: update mempool stats and fee estimate data when updating mempool table

src/app/txid/[txId]/redesign/tx-summary/SummaryItem.tsx
=> fix: txid page: usd value

.github/workflows/ci.yml, .github/workflows/deploy.yml
This enables signed commits of bot deployments
Was tested in a dev deployment [here](https://github.com/hirosystems/k8s/commit/be77c733b736bfde676f1ecfad084d4fc54cac39)
=> ci: switch to main deploy branch; add gpg

src/ui/Badge.tsx
=> fix: block url

src/app/_components/RecentBlocks/BtcBlock.tsx, src/app/_components/RecentBlocks/StxBlock.tsx, src/ui/Badge.tsx
[](fix: blocks badge hydration issue)
=> fix: blocks badge hydration issue

src/common/utils/transactions.tsx
Badge color on the contract deploy badge needeed fixing
=> fix: fixed the contract deploy badge color

src/common/constants/env.ts
Understand all env vars needed for Vercel migration
Will remove after migration is completed
=> feat: debug env vars

src/app/txid/[txId]/redesign/function-called/function-call-function-params-utils.ts
=> chore: trying to deploy main

src/app/txid/[txId]/redesign/function-called/function-call-function-params-utils.ts
=> chore: deploying main

src/app/blocks/components/BlocksTable.tsx, src/app/blocks/components/hooks/useBlocksTableData.ts, src/app/blocks/queries/useBlocksV2Queries.ts, src/common/queries/useBurnBlocksInfinite.ts
Since we're no longer user "load more" to paginate, we need to move away from infinite query and use https://tanstack.com/query/v4/docs/framework/react/guides/paginated-queries
=> fix: update blocks page pagination

README.md
=> feat: test deployment
