stx-labs/explorer

- next.config.js
- src/common/api/transactions.tsx
- src/models/index.ts
- src/models/transaction.interface.ts
- src/pages/api/transactions.ts
- src/store/transactions/reducer.ts
- tsconfig.json
For time being, this type has been copied from the sidecar repo.
Going forward, I hope we can have all these types generated from the JSON schmas so there's no duplication.
> feat: hook up to api, include transaction interface

- src/components/page.tsx
- src/components/recently-viewed.tsx
- src/components/search-bar.tsx
This adds the recent tx component as a drop down to the search bar on transaction pages. See the gif below:
> feat: search with recent tx dropdown

- src/common/hooks/use-color-mode.tsx
- src/common/hooks/use-dark-mode.tsx
- src/common/utils.tsx
- src/components/color-modes.tsx
- src/components/footer-links.tsx
- src/pages/_app.tsx
- src/pages/index.tsx
This improves the way color mode variables are handled, and allows the user to toggle color modes with no regard to their system settings. The application will choose the color mode of the system first, unless there is a cookie present (meaning the user had previously toggled color modes).
> feat: toggle color mode

- src/common/hooks/use-recently-viewed-tx.tsx
- src/components/search-bar/index.tsx
Previously the use-recently-viewed hook would not save the last viewed item immediately, you'd have to navigate away from the tx page and it would show up then. Now it will save immediately and be available when you view the list.
> fix: update recently viewed hook to save faster

- src/components/popover/popover.tsx
- src/components/popover/types.ts
- src/components/popover/use-popover.tsx
- src/components/sandbox/common.tsx
- src/components/sandbox/contract-call.tsx
- src/components/sandbox/contract-call/functions.tsx
- src/components/sandbox/contract-deploy.tsx
- src/components/search-bar/index.tsx
- src/components/select.tsx
This adds a nice to have for when using the contract call functionality of the sandbox. Typically you'd copy the fully realized name of the contract, eg `ST14Z2G3JTG8805N2CCVXG85XGFJP6PME385X69JG.hello`. You can now paste this into the address field, and it will automatically split the address and name, filling both fields with the values.
This also adds the drop down to all function calls for selecting the post condition mode. Eventually we will have a post conditions component that will allow the user to add any possible combination of post conditions.
> fix: auto split contract name, add post condition mode select

- src/components/status.tsx
This takes into account two new options for the status of a transaction:  `abort_by_response` `abort_by_post_condition`. This PR only makes sure that nothing breaks. In a different PR I will address adding messaging to help folks understand better why the transaction failed. Related: https://github.com/blockstack/stacks-blockchain-sidecar/pull/126
> fix: account for new status options

- src/common/api/transactions.tsx
- src/common/utils.tsx
- src/pages/transactions.tsx
This implements the new feature of being able to specify which types of transactions we want to search for via the tx endpoint of the sidecar. This is much faster than before, since we don't need to show coinbase transactions.
> fix: use new types param for tx list

- src/pages/sandbox/index.tsx
@dantrevino noted in Discord having to re-auth with connect despite having authed with other apps. Seemingly owning to the auth origin pointing to a netlify build. I believe this can now be updated.
> fix: out-of-date auth origin

- src/common/sandbox/index.ts
This PR
* encodes function names before calling the stacks node endpoint for read-only functions
* fixes #235
> fix: encode read-only function names #235

- .github/workflows/explorer.yml
Adding workflow file to build and push docker images to hub.docker.com 
Tags are based off of https://github.com/crazy-max/ghaction-docker-meta , and should build for any branch
1. Motivation for change: Migrate build/CI away from quay to dockerhub (inline with other work)
2. What was changed: Added file `.github/workflows/explorer.yml`
3. How does this impact application developers: up to date docker images (low to no impact for devs i would imagine)
https://github.com/blockstackpbc/devops/issues/480
No
No
N/A
> Add workflow to build docker image

- src/common/api/network.ts
- src/common/hooks/use-network-add-form.tsx
- src/common/hooks/use-network-mode.ts
- src/common/hooks/use-stacks-info.ts
- src/common/types/network.ts
- src/common/utils.tsx
- src/common/utils/addresses.ts
- src/components/address-not-found.tsx
- src/components/balances/stx-balance-card.tsx
- src/components/block-not-found.tsx
- src/components/btc-anchor-card.tsx
- src/components/function-summary/args.tsx
- src/components/metaverse-bg.tsx
- src/components/network-items.tsx
- src/components/network-mode-banner.tsx
- src/components/page.tsx
- src/components/stacking.tsx
- src/components/stacks-token-vesting-card.tsx
- src/components/tx-not-found.tsx
- src/pages/404.tsx
- src/pages/_error.tsx
- src/pages/address/[principal].tsx
- src/pages/block/[hash].tsx
- src/pages/blocks.tsx
Test address page: https://explorer-7f6db7ey3.vercel.app/address/SP97B09CCCHE31FTHR97ZKAF0VF3DD1XR57MZSWX?chain=testnet
This PR pulls data for addresses that have vesting data and displays a card with some information:
I've also added the ability to display when someone is viewing a mainnet/testnet address in the inverse context, and update the url by user action:
> Show vesting data

- src/common/constants.ts
Makes the default polling default to an env var
> fix: as env var

- src/common/api/transactions.tsx
- src/common/api/utils.ts
- src/common/hooks/use-chain-mode.ts
- src/common/hooks/use-network.ts
- src/common/lib/blocks.ts
- src/common/lib/pages/home.tsx
- src/common/render-tx-page.tsx
- src/common/utils/accounts.ts
- src/components/modals/different-network.tsx
- src/components/network-items.tsx
- src/components/tabbed-transaction-list.tsx
- src/components/transaction-list.tsx
- src/components/tx/smart-contract.tsx
- src/pages/index.tsx
- src/pages/txid/[txid].tsx
- src/store/network.ts
In the Stacks Blockchain, contracts are able to be participants in transactions. This is typically in the form of being the contract that is called for a function call transaction. This PR adds a list of transactions for any contract, giving the user the ability to see all calls to said contract.
In the same way that contracts are able to participate in transactions, they can also hold balances of STX, NFTs, and FTs. This PR implements the same balance card component that a user would see if they were on any other address page
- Fixes network switching bugs
- Makes it so the server is aware of a chain param passed, fixing a bug where links to testnet data would not render the correct open graph data
- The blocks list on the homepage now uses react-query just as the transaction lists do
- …
> Show transactions, balance on contract deploys, other misc fixes

- package.json
Modifies the semantic-release message on new releases to ensure they _don't_ contain the `[skip ci]` modifier. [Github now respects this modifier whereas before they didn't](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/) so this change is necessary to repair the workflow linkage which would build and upload a new Docker image tag upon release.
For details refer to issue https://github.com/blockstackpbc/devops/issues/621
No.
No.
> chore: don't skip ci on releases

- src/common/api/accounts.ts
- src/components/transaction-details.tsx
- src/pages/address/[principal].tsx
fixing #322
1. Motivation for change
Oftentimes, transactions are pending for a long time due to nonce issues. It is not possible to review the nonces in the explorer, so the API is used.
2. What was changed
Adding a nonce field to the account and transaction page
No
Tested locally and compared to API results.
> feat: add nonce to tx and account page

- src/components/balances/stx-balance-card.tsx
As an interested in the project, I would like to improve the text selection in the address balance. This is needed because it isn't possible to select the balance with click or double click.
This PR was done taking into account the `#418`,  I tested it in windows 10 with notepad, VSCode and Sticky Notes, but I can't reproduce the multi-line paste issue, so, I did an improvement in the select
For details refer to issue #418 by @markmhx
No
No
1. Go to the page http://localhost:3000/address/ST2X2FYCY01Y7YR2TGC2Y6661NFF3SMH0NGXPWTV5?chain=testnet
2. select the STX Balance.
Expected result: it should select all the text.
> fix: select the balance with one click

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
Updates the  concurrency configuration for the `CI/CD` and `deploy` workflows to be less restrictive. With the current settings, you're unable to deploy to an environment for any branch or tag if there's already a deployment _pending_ (read: not in-progress, but waiting for review). [Example can be found here](https://github.com/blockstack/explorer/actions/runs/939847060).
This change lessens the concurrency restriction without removing it. It will now only consider concurrency blockages if there's a deployment pending for the same git ref for the same environment. It will also auto-cancel the older pending deployment to unblock the newer deployment so it can be approved.
[More info on concurrency can be found here if interested.](https://docs.github.com/en/actions/reference/workflow-synta …
> ci: change deploy concurrency

- src/components/transaction-details.tsx
This PR fixes the timestamp on the microblock transaction page to be the `parent_burn_block_time`.
For details refer to issue #515
> fix: microblock tx parent burn block time

- src/components/add-network-form.tsx
- src/components/modals/unlocking-schedule.tsx
- src/sandbox/components/views/deploy/contract-name.tsx
As a Blockstack developer, when I type in an example contract name, I should be able to see the text input value regardless of what theme I am using at the time.
This PR applies the `color` attribute to the "Contract Name" field on the contract-clarity editor so that when in `dark` theme the text inside this box is still visible.
Reported:
Fixed:
<video src='https://user-images.githubusercontent.com/16845892/130733366-2153879d-0905-4aeb-bbe8-d71d5e719d8a.mov'/>
N/A
N/A
Provide context on how tests should be performed.
1. Is testing required for this change?
No
2. If it’s a bug fix, list steps to reproduce the bug
Load clarity code editor page in sandbox and switch to dark theme. Note the field value is same as input background
- [-] Code is commented where needed
- [-] Unit test coverage …
> [Bug] Apply Dark mode text color to input on Contract Deploy field

- src/features/search/items/tx-result-item.tsx
This PR fixes the search to include transactions in the mempool.
For details refer to issue #530 
- Search for a tx id in the mempool and make sure it lists/links to it correctly.
> fix: add mempool tx to search

- src/common/page-queries/account.ts
- src/common/utils/accounts.ts
- src/components/balances/stx-balance-card.tsx
- src/components/stacking.tsx
- src/hooks/currently-in-view-hooks.ts
- src/hooks/use-stacks-info.ts
- src/store/currently-in-view.ts
- src/store/info.ts
This PR fixes the missing stacking cycle information on the address details page.
For details refer to issue #520 
- Make sure you have locked STX
- Go to your address page
- Verify you can see the stacking information
> fix: stacking cycle info

- src/components/tabbed-transaction-list.tsx
This fixes an infinite loop that was occurring when switching b/w the transaction tabs.
For details refer to issue #538
> fix: transaction tabs

- src/components/balances/stx-balance-card.tsx
- src/components/item-icon.tsx
- src/components/transaction-item.tsx
- src/features/blocks-list/block-list-item.tsx
- src/features/blocks-list/microblock-list-item.tsx
This PR fixes dark mode styling so at least text/icons show up until we actually design the explorer dark mode. If there are designs to reference and make further corrections on this, please let me know (cc @jasperjansz).
For details refer to issue #528
> fix: dark mode

- src/components/modals.tsx
- src/pages/address/[principal].tsx
- src/pages/txid/[txid].tsx
We currently use `withInitialQueries` from `jotai-query-toolkit`, this HOC [wraps the page into a new Jotai provider](https://github.com/fungible-systems/jotai-query-toolkit/blob/3cdba6c65d09c615b1851a2f9c02db3273c60848/src/nextjs/intial-queries-wrapper.ts#L30-L34).
This creates an isolated state for each wrapped page, which prevents it from updating the state outside page scope (in this case, modal state).
A **temporary** fix could be to move this modal to the pages where it's being used. We probably should aim towards eliminating `jotai-query-toolkit` in the near future.
#561
> fix: View schedule for addresses with unlocking tokens

- package.json
- src/common/api/client.ts
- src/common/constants.ts
- src/common/utils.tsx
- src/components/balances/principal-token-balances.tsx
- src/components/balances/token-asset-list-item.tsx
- src/components/post-conditions.tsx
- src/components/tx-events.tsx
- src/store/accounts.ts
- yarn.lock
This isn't the most DRY implementation, but bc of how these pages/components are built, this might be the best solution until we can give the explorer more attention and remove query atoms like we have done in the web wallet. The ft/nft tokens really need to be handled separately so that the fetch for data isn't done conditionally (which breaks the rules of hooks, so can't do it). This does resolve issues with missing ft decimals for now.
Issues: #402, #506, and #604
> feat: add sip 10 decimal support

- src/features/blocks-list/hooks.ts
- src/features/blocks-list/microblock-list-item.tsx
A temporary solution to prevent /blocks page from spamming API. Txs count will be added back once [API support](https://github.com/hirosystems/stacks-blockchain-api/issues/1048) is implemented.
closes: #640
> fix: remove microblock txs count

- src/components/modals.tsx
- src/pages/_app.tsx
- src/pages/address/[principal].tsx
- src/pages/txid/[txid].tsx
The application error in the linked issue is hard to reproduce with a running local env, so debugging is tricky on this. The error is telling us to move the Suspense boundary higher in the component tree. I believe this was (perhaps) introduced with the changes in this PR? https://github.com/hirosystems/explorer/pull/614
@He1DAr any thoughts on this solution to try? I can't say for sure it fixes the error bc I can't reproduce it locally.
> fix: move suspense

- src/common/utils.tsx
- src/components/balances/stx-balance-card.tsx
Fix for https://github.com/hirosystems/explorer/issues/625
Fix multiple issues at once related to localization.
> fix: locale decimal separator issue

- .github/workflows/ci.yml
Leverages a new feature in our deployment action to specify Docker image digests instead of the general tag on CI deployments.
This helps resolve the scenario where two commits are pushed to a branch, and the first commit gets deployed, but the second one results in a no-op deployment since the tag didn't change.
Resolves https://github.com/hirosystems/devops/issues/927
[Working](https://github.com/hirosystems/explorer/actions/runs/2204240909)
> ci: docker image digests

- .github/workflows/deploy.yml
Uses the Github commit reference if no tag is passed to the deploy workflow. Tags should now deploy without getting re-built, while build + deploying branches is now functional again.
Confirmed working [1](https://github.com/hirosystems/explorer/runs/6133934158?check_suite_focus=true) & [2](https://github.com/hirosystems/explorer/runs/6134041549?check_suite_focus=true)
Closes https://github.com/hirosystems/devops/issues/930
> ci: use github ref if tag is not passed to deploy workflow

- src/common/api/client.ts
- src/common/state/network-slice.ts
- src/components/meta/transactions.tsx
- src/pages/_app.tsx
- src/pages/address/[principal].tsx
- src/pages/index.tsx
- src/pages/txid/[txid].tsx
- src/store/accounts.ts
- src/store/api-clients.ts
- src/store/currently-in-view.ts
Exploring a fix to devnet (localhost) server-side data fetching. Basically skipping prefetch, which will cause the client to do the requests instead of the server.
> feat: skip prefetch for devnet

- .github/workflows/deploy.yml
Prevent anything but tags from being deployed to production.
> ci: only allow tag deployments to prod

- src/features/address-page/address-summary.tsx
> fix: display 0 instead of blank in address summary

- src/components/header.tsx
- src/features/status-bar/status-bar.tsx
Fetch and display status with a link to the status page `https://status.hiro.so/`
closes #780
> feat: fetch and display status

- src/components/btc-stx-block-links.tsx
- src/components/transaction-details.tsx
- src/components/tx/coinbase.tsx
- src/components/tx/contract-call.tsx
- src/components/tx/poison-microblock.tsx
- src/components/tx/smart-contract.tsx
- src/components/tx/token-transfer.tsx
- src/features/blocks-list/block-list-item.tsx
- src/pages/block/[hash].tsx
Create a new component `<BtcStxBlockLinks />` to render both STX and BTC block height with links in all places where we want to show block details.
> feat: BTC and STX block height links

- src/modules/TransactionList/components/TxsListWithTabs.tsx
This adds back the tabs header (Confirmed, Pending) for the skeleton on the home page transaction list
cc: @He1DAr 
Before:
After:
> fix: add tabs in home page skeleton

- src/components/btc-anchor-card.tsx
Closes https://github.com/hirosystems/explorer/issues/826
Within the "Bitcoin anchor" section on the right side of the block page, the "Bitcoin block height" text will have a link to the blockchain.com explorer.
> feat: add a link to the blockchain.com explorer from the bitcoin block height on the block page

- src/components/btc-anchor-card.tsx
- src/components/btc-stx-block-links.tsx
- src/components/function-summary/value.tsx
- src/features/blocks-visualizer/index.tsx
Closes #533 
Link to mempool.space rather than blockchain.com for all external btc links. Also ensures path is prefixed appropriately for mempool.space links while using testnet
> feat: change all external btc links to mempool.space

- .husky/pre-commit
- package.json
- src/common/hooks/use-current-prices.ts
- src/components/balances/stx-balance-card.tsx
- src/components/btc-stx-price.tsx
Closes #853 
Shows USD price alongside all balances on the address page.
> feat: show usd values alongside balances on address page

- src/common/utils.tsx
- src/components/balances/stx-balance-card.tsx
- src/components/btc-stx-price.tsx
- src/components/transaction-details.tsx
Closes #852 
Displays USD values alongside the amount & fee on the Transaction page.
> feat: show usd values alongside amount and fees on transaction page

- src/common/utils.tsx
- src/components/transaction-details.tsx
- src/components/transaction-item.tsx
- src/modules/TransactionList/components/MempoolTxsListItem.tsx
- src/modules/TransactionList/components/TxsListItem.tsx
Show USD values within transaction lists.
On narrow screens, the USD value will stack:
> feat: show usd values within transaction lists

- .husky/pre-commit
Removing precommit formatting check because it's slow and devs can configure their own. re: https://github.com/hirosystems/explorer/pull/855#discussion_r966660812
> chore: remove precommit formatting check, allow devs to configure their own

- Dockerfile
- src/components/app-config.tsx
- src/pages/_document.tsx
* Moves the ARGs directives out of the global scope and instead sets it in each dockerfile stage. The workaround to keeping these ARGs global while having them set correctly and persist in each stage is arguably more difficult to maintain and more confusing than this configuration. If it were a longer dockerfile with more stages, it may be warranted.
* Removes the ENVs from the first stage since they only need to be persisted to the image in the last stage, and are still made available during build-time in the first stage through the ARGs.
> ci: fix ENV var propagation in Dockerfile

- src/components/tx-events.tsx
There is an issue with the 'load more events' alignment
> fix: align load more events

- src/components/section-footer-button.tsx
To reproduce
1. Open Explorer, select Network -> Testnet
2. Under “Recent Blocks”, click “View all blocks”
3. Observe that the /blocks page is now showing Mainnet blocks instead of testnet
Same issue with "View all transactions"
> fix: view all blocks and view all transactions incorrect redirect

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
The current settings for the Explorer repo _should_ allow the default GITHUB_TOKEN to do what it needs to do. If not, then we'll have to reintroduce the previous token only where necessary.
Related to https://github.com/hirosystems/devops/issues/1044
> ci: update github token used for most steps to default token

- src/modules/sandbox/components/SideNav.tsx
fixes https://github.com/hirosystems/explorer/issues/851
added a tooltip to navigation icons in the sandbox
https://user-images.githubusercontent.com/16448321/199727768-14c8e866-ecf0-4433-b7ec-0a5605c60083.mp4
> feat: add tooltip to navigation icons in sandbox

- src/components/function-summary/result.tsx
I ran into this bug with a contract call that has a "tuple" return type, and one of the keys has a 'none' value. The page crashes in that case.
This was just on my local devnet, so I don't have a public reproduction available unfortunately.
I remember this code 😅 it's such a nightmare to get strong types
> fix: handle tuple result when value is 'none'

- src/pages/txid/[txid].tsx
fixes https://github.com/hirosystems/explorer/issues/902
`useQuery` fetches the non-existent tx several times, but the component doesn't handle the error state so it looks like it's loading forever.
added an error check so that after a few failed fetching attempts it would display the `TxNotFound` component.
https://user-images.githubusercontent.com/16448321/199724219-4b792288-1ade-4759-a1e7-588721595840.mp4
local test url: http://localhost:3000/txid/0xbb7bcc79a698c665edcd01b934967b012c5329ba6b88356f4bf50ab0d9551e61?chain=mainnet
> fix: add error check for non-existent transaction on txid page

- src/common/api/utils.ts
- src/common/constants/network.ts
- src/common/state/network-slice.ts
- src/common/types/network.ts
- src/components/meta-head.tsx
- src/components/network-items.tsx
- src/components/network-mode-banner.tsx
- src/modules/sandbox/hooks/useUser.ts
- src/pages/_app.tsx
Addresss issues:
closes #949, #950, and #955
Issue:
The network switcher in the header was not working. The two main issues I identified were:
1. The initial bootstrapping of the app was not respecting the chain search param in the url. The query object from Nextjs is undefined
2. In multiple places in the code, "devnet" was not regarded as a valid network mode, which resulted in UIs that were confusing because the devnet network would be selected, but the UI would display labels for testnet.
Solution: 
1. I am manually checking the url search params and reconciliing my results with nextjs's results
2. I made devnet a first class citizen as far as networking modes go
Testing:
I am manually testing that the issues noted above have been fixed
> Fix: network switching

- src/modules/sandbox/components/ContractCall/FunctionView.tsx
Fixes the issue where you can still click the "Add Post Condition" button even though it is disabled.
> fix(disabled-pc): Disabled Post Condition Button should not be clickable

- src/app/sandbox/components/ContractCall/FunctionView.tsx
- src/app/sandbox/utils.ts
This PR
* handles non-tuple optional function arguments in the sandbox
This change is important for using city coin contracts, wrapper pox contracts, etc.
> fix(sandbox): handle optional function args (#956)

- src/app/sandbox/components/Argument/TupleArgumentInput.tsx
- src/app/sandbox/components/ContractCall/FunctionView.tsx
- src/app/sandbox/utils.ts
This PR
* fixes #1069 
* adds handling for optional tuples. If one tuple value is empty, the optional tuple is represented as `none`
> fix(sandbox): handle optional tuples better

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
* Updates action versions
* Uses native concurrency features, removing extra job to perform this function
* Adds job to deploy to dev environment, with auto-deploy feature similar to stg
* Updates all deploy jobs to use new environments
> ci: update continuous deployment workflows

- src/app/common/utils/sandbox.ts
- src/app/sandbox/components/ContractCall/AvailableFunctionsView.tsx
- src/app/sandbox/components/ContractCall/FunctionView.tsx
- src/app/txid/[txid]/SmartContractPage/ContractTabs.tsx
This PR
* hides pox-2.stacks-increase calls in preparation for Stacks 2.2
* in the sandbox's list of available functions
* in the contract page's list of available functions
* in the sandbox deep link http://localhost:3000/sandbox/contract-call/SP000000000000000000002Q6VF78.pox-2/stack-increase?chain=mainnet
How to test?
Check the list of available functions on the following pages:
* visit /txid/SP000000000000000000002Q6VF78.pox-2?chain=mainnet 
* visit sandbox/contract-call/SP000000000000000000002Q6VF78.pox-2?chain=mainnet
* visit sandbox/contract-call/SP000000000000000000002Q6VF78.pox-2/stack-increase?chain=mainnet
> feat: hide pox-2.stack-increase

- jest.config.js
- src/app/sandbox/components/ContractCall/DefaultView/SearchContractsForm.tsx
- src/app/sandbox/editor-config/define-theme.ts
- src/features/status-bar/status-bar.tsx
Closes [ Explorer dev Error: Illegal value for token color: #000 #1140 ]
Fixes issue: Explorer dev Error: Illegal value for token color: # 000
Added proper hexadecimal notation for colors.
In most cases, colors are represented using different color models such as RGB (Red, Green, Blue) or hexadecimal notation. In the case of hexadecimal notation, colors are represented by a six-digit code preceded by a hash symbol (#), such as #000000 for black.
> fix: added proper hexadecimal notation for colors

- jest.config.js
- src/features/address-page/address-summary.tsx
Closes [ Incorrect last executed nonce shown #878  ]
Fixes issue: Incorrect last executed nonce shown
Added correct ternary condition. 
Previous Image: 
Image after fix: 
File changed
`explorer/src/features/address-page/address-summary.tsx`
> fix: fixed the lastExecutedTxNonce value

- .github/workflows/integration-tests.yml
- docs/getting-started.md
- docs/how-to-guides/build-explorer.md
- docs/overview.md
- package.json
- playwright.config.ts
Issues:
1. In this repository, the use of Pnpm for installing dependencies is mandatory. It would be beneficial to remove other package managers and prioritize Pnpm instead.
2. The readme.md file contains the correct steps, but the files within the docs folder have not been updated.
4. The hirosystem/docs repository retrieves content from the outdated docs folder. Please refer to the attached image.
<br><br>
Changes:
1. [X] Updated all md files under docs folder
2. [X] All yarn commands have been replaced with Pnpm commands.
6. [X] I have verified, Application runs locally after the changes by running `pnpm dev`
<br><br>
Image - Code snippet - `hirosystem/docs`
<br>
cc @andresgalante
> Documentation Mismatch | PNPM usage

- src/app/common/components/StxPriceButton/index.tsx
closes #1125
When Coingecko's API limit is exceeded, it results in an undefined value. In such cases, if the historicalData is undefined, we refrain from displaying the historical data (USD value) on the frontend.
Files changed
src/app/common/components/StxPriceButton/index.tsx
> fix: StxPriceButton click gives 'NaN' on historical data

- src/app/txid/[txid]/ContractCall/index.tsx
- src/app/txid/[txid]/SmartContractPage/index.tsx
- src/components/post-conditions.tsx
closes https://github.com/hirosystems/explorer/issues/1101
Closes Display dollar amount on Stacks tokens #1101 
Fixes issue:  Display dollar amount on Stacks tokens in post conditions
Added StxPriceButton to post conditions
Feature image
Files changed
post-conditions.tsx
ContractCall/index.tsx
> feat: add stx price button to post conditions

- src/app/common/components/tx-lists/tabs/TxListTabs.tsx
- src/components/CSVDownloadButton.tsx
- src/components/filter-button.tsx
Fixes https://github.com/hirosystems/explorer/issues/1188
> fix: make action buttons from TxListTabs semantic and aligned

- src/common/utils/accounts.ts
- src/components/balances/principal-token-balances.tsx
- src/components/balances/token-balances-row.tsx
This PR closes #1235 
Holdings indicator in both left and right panels are consistent now.
> fix: holdings indicator incosistent

- src/common/context/GlobalContext.tsx
- src/common/context/__tests__/GlobalContext.test.tsx
- src/components/__tests__/add-network-form.test.tsx
- src/components/add-network-form.tsx
When opening the Stacks Explorer with an API URL in the query string (`api`), if that network does not exist and it is a valid Stacks API URL, add it to the list of custom networks. This allows an external application to link to the Explorer with a prefilled custom Stacks network, and the Explorer will automatically open to that network.
Also, support custom networks whose Base URL includes a path (fixes #1257).
> feat: add custom network using query param

- src/app/sandbox/components/ContractCall/ReadOnlyField.tsx
Disabling react-query cache when calling read-only functions.
closes #1218
> fix: read-only function call caching

- src/app/components/BlockList/__tests__/__snapshots__/MicroblockListItem.test.tsx.snap
- src/app/components/NavBar/__tests__/__snapshots__/DesktopNav.test.tsx.snap
- src/app/components/NavBar/__tests__/__snapshots__/MobileNav.test.tsx.snap
- src/app/txid/[txid]/ContractCall/TxDetails.tsx
- src/app/txid/[txid]/TxDetails/Broadcast.tsx
- src/app/txid/[txid]/TxDetails/Broadcasted.tsx
- src/app/txid/[txid]/TxDetails/__tests__/Broadcast.test.tsx
- src/app/txid/[txid]/TxDetails/__tests__/__snapshots__/Broadcast.test.tsx.snap
Close [#1030](https://github.com/hirosystems/explorer/issues/1030)
On the transaction details page, for pending transactions (mempool), I added a new component for receipt time labeled "Broadcasted"
> feat: show receipt time on transaction page

- src/common/utils.spec.ts
- src/common/utils.ts
- src/components/function-summary/result.tsx
- src/components/function-summary/value.spec.ts
- src/components/function-summary/value.tsx
closes https://github.com/hirosystems/explorer/issues/1156
Closes Incorrect display of optional in tuple result #1156
Fixes issue: Incorrect display of optional in tuple result 
Rectified the incorrect tuple value
Feature image
> fix: Rectified the incorrect tuple value

- src/app/sandbox/deploy/LeftSection.tsx
This adds a button to import sandbox contract code into the platform as a project
See https://github.com/hirosystems/platform/issues/740
designs [here](https://www.figma.com/file/zQt1ia4SlVM8t6c0jmFWEy/Working-File?type=design&node-id=1273%3A33751&mode=design&t=B7LUZ1KyGobDCypA-1)
> fix: add button to save contract to Hiro platform

- src/app/sandbox/faucet/page.tsx
- src/app/txid/[txid]/TxDetails/__tests__/__snapshots__/Broadcast.test.tsx.snap
> feat: display faucet error message

- .github/workflows/code-check.yml
- .github/workflows/lighthouse.yml
- .github/workflows/linting.yml
- Dockerfile
Suggested fix for issue 1323 - Docker build failing.
The build is breaking because of a new release of pnpm being incompatible. This should probably be fixed by understanding why the new release is breaking, but this should work for now.
> specified pnpm version

- src/common/contracts/hello-world-contract.tsx
- src/common/contracts/kv-store.tsx
- src/common/contracts/status.tsx
- src/common/contracts/stream.tsx
Most of the contract examples in the explorer sandbox have a few syntax error. Especially on tuple definition (and sometimes unnecessary tuples).
I fixed the contract and made the coding style (lines breaks and indentation) more consistent over the examples
> fix: sandbox clarity examples syntax

- next.config.js
This prevents the reuse of explorer.hiro.so inside an iframe.
> fix: prevent iframe injection in another page

- src/app/_components/BlockList/LayoutA/__tests__/__snapshots__/BlockListWithControls.test.tsx.snap
- src/app/_components/NavBar/BtcStxPrice.tsx
fixes header icon sizes
With components that are using circle and and grid, I have observed that the size property behaves inconsistently and doesn't correctly apply the chakra ui 1: 4rem scalling system. Therfore, I changed the numbers to hardcoded pixles.
> fix(header-icons): fixed header icons

- package.json
- pnpm-lock.yaml
- src/app/_components/BlockList/LayoutA/__tests__/__snapshots__/BlockListWithControls.test.tsx.snap
- src/app/transactions/MempoolFeePieChart.tsx
- src/app/transactions/MempoolFeeStats.tsx
- src/app/transactions/TransactionTypeFilterMenu.tsx
- src/app/txid/[txId]/TxDetails/Fees.tsx
- src/app/txid/[txId]/TxDetails/__tests__/Broadcast.test.tsx
- src/common/components/FilterMenu.tsx
- src/common/components/modals/unlocking-schedule.tsx
- src/common/queries/useMempoolFee.ts
- src/common/queries/useMempoolTxStats.ts
- src/features/txs-list/tabs/CSVDownloadButton.tsx
- src/ui/Grid.tsx
- src/ui/MenuButton.tsx
- src/ui/theme/colors.ts
- src/ui/theme/theme.ts
Adds the mempool header
Resolves mempool header portion of this PR - https://github.com/hirosystems/explorer/issues/1430
Figma - https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=6092%3A14261&mode=dev
> feat: mempool header

- src/app/PageClient.tsx
- src/app/_components/BlockList/LayoutA/BurnBlock.tsx
- src/app/_components/BlockList/UpdatedBlockList.tsx
> feat: Nakamoto homepage blocks view

- src/app/txid/[txId]/ContractCall/index.tsx
- src/app/txid/[txId]/TxPage.tsx
Minimizing excessive code splitting to decrease initial load and allow page sections to be loaded simultaneously.
> feat: tx page performance improvement

- src/app/_components/BlockList/Sockets/use-stacks-api-socket-client.ts
- src/app/_components/BlockList/Sockets/useSubscribeBlocks.ts
I noticed a looping socket error on localhost on mainnet.
The socket hook is trying to use the client set in state to close the socket but the state client is not defined when an immediate connection error takes place, which leads to the disconnect code to never run. 
Now I am using the client var reference in the function to disconnect in addition to calling the disconnect code on the client in state if it exists
> fix(socket-errors): fixed

- docs/how-to-guides/stacks explorer sandbox
I plan to come back to this, just wanted to submit these changes in case I lose them. #githubnoob
> Stacks Explorer Sandbox - feature guide

- src/app/getTokenPriceInfo.ts
- src/app/stxPrice/route.ts
Add caching to token price requests with revalidation every 10 minutes. Cached request saves ~300ms of initial load.
Before:
After:
> feat: token price caching

- src/app/_components/NavBar/NetworkLabel.tsx
- src/app/_components/PageWrapper.tsx
- src/common/context/GlobalContext.tsx
- Change the banner text
- Rename "Stacks Testnet" to "Primary Stacks Testnet" on the network selection
- Move “Nakamoto Testnet” above “Stacks Testnet (archive)” in the dropdown
> feat: network dropdown update

- .github/workflows/ci.yml
This pull requests add ARM builds to docker so one can host the explorer on an ARM server. The approach is to only do amd build on prs to not increase the build time and build both arm + amd on the main branch for the release.
Related: I added ARM support to the stacks-blockchain-api in this pr https://github.com/hirosystems/stacks-blockchain-api/pull/1947
> feat: add docker build for arm

- src/app/block/[hash]/PageClient.tsx
- src/app/txid/[txId]/TxDetails/__tests__/__snapshots__/Broadcast.test.tsx.snap
- src/common/hooks/useInfiniteQueryResult.ts
Issue: https://github.com/hirosystems/explorer/issues/1376
I added this canonical key value pair when the block is not canonical to show when the block is orphaned or not. 
@GinaAbrams Do you think this is ok? Or do you want to design this differently?
> fix(orphan-blocks): added kv pair to show canonical status

- src/app/_components/BlockList/BlockListItem.tsx
- src/app/_components/BlockList/LayoutA/useBlockList.ts
- src/app/_components/BlockList/UpdatedBlockList.tsx
- src/app/block/[hash]/PageClient.tsx
- src/common/components/transaction-item.tsx
Context - https://hiropbc.slack.com/archives/C03TU42NL05/p1728686112307179
The Stacks block timestamp is inconsistent on the transaction page vs the blocks list page on Primary testnet.
block page uses burn_block_time while block list uses block_time
Both should use block_time
> fix: block time

- src/features/txs-list/ConfirmedTxsList.tsx
- src/features/txs-list/tabs/TxListTabs.tsx
The filter state was getting reset because when the load more was clicked and the request was in flight we returned different jsx, loading jsx, which wiped the filter jsx from the dom, resetting the filters state.
https://github.com/hirosystems/explorer/issues/1828
> fix: fixed filters resetting when clicking load more

- src/app/txid/[txId]/TxPage.tsx
Context https://github.com/hirosystems/explorer/issues/1854
The pending blocks ui doesnt make sense for any network that is naka 3.0 ready, so we are going to remove it
https://github.com/hirosystems/explorer/issues/1854
> fix: removed pending blocks ui from everything but mainnet

- src/stories/Spacing.stories.tsx
- src/ui/theme/theme.ts
Adding design system spacing explicitly to the theme
https://github.com/hirosystems/explorer/issues/1842
> feat: adding spacing to theme

- src/common/components/__tests__/add-network-form.test.tsx
- src/common/components/modals/AddNetwork/__tests__/utils.test.ts
- src/common/components/modals/AddNetwork/utils.ts
- src/common/context/GlobalContextProvider.tsx
- src/common/context/__tests__/GlobalContext.test.tsx
- src/common/context/useGlobalContext.ts
Instead of determining http or https based on whether the urlobj contains localhost, we will base it directly off the protocol that is included in the url passed. If the protocol does not match http or https we will default to https
closes https://github.com/hirosystems/explorer/issues/1786
> fix: fixed the add network bug

- src/app/signers/SignerDistributionLegend.tsx
- src/app/signers/consts.ts
Updating xverse signer keys by associatiing previosuly unassociated signer keys to Xverse
This creates the first situation where there are more than one signer key associated with an entity
**NB. I am aggregating the weight_percent of all signer keys that are associated with the same entity in the distribution legend**
Closes #1880 and #1882
> feat: updated xverse signers

- src/app/_components/Stats/StxSupply/index.tsx
- src/common/queries/useStxSupply.ts
Fixes supply stats on the homepage.
Slack context: https://hiropbc.slack.com/archives/C03TU42NL05/p1730334206249929?thread_ts=1730330803.165729&cid=C03TU42NL05
the explorer is dividing circulatingSupply = total_liquid_supply_ustx / MICROSTACKS_IN_STACKS = 1501825000.29185
by
totalSupplyNumber = unlocked_stx = 1498769444.73627
total_liquid_supply_ustx is taken from /v2/pox
unlocked_stx is taken from api.infoApi.getStxSupply({})
Interestingly, total_stx, taken from api.infoApi.getStxSupply({}), is 1498769444.73627, which is the same as unlocked_stx, as well as less than total_liquid_supply_ustx.
I can see that the response for api.infoApi.getStxSupply({}) has changed. It now includes total_stx_year_2050, which we weren't using before. I will fix that.
The main issue is that we are taking …
> fix: fixed supply #s

- src/app/txid/[txId]/TxDetails/BlockHeight.tsx
Use block time in tx page when available instead of burn block time
> feat: use block time in tx page

- src/features/txsFilterAndSort/FilterButton.tsx
Display tenure change filter for all networks.
> feat: display tenure change filter

- src/app/txid/[txId]/Alert.tsx
- src/app/txid/[txId]/TxAlerts.tsx
- src/app/txid/[txId]/useWhyDidMyTxFail.ts
Display logs from why-did-my-tx-fail for failed txs
closes #1929
> feat: why did my tx fail

- src/app/token/[tokenId]/Tabs/index.tsx
- src/app/token/[tokenId]/consts.ts
- src/app/tokens/utils.ts
Adding confirmed and pending deposit tabs just for the sbtc token page
> feat: added confirmed and pending deposits

- src/app/token/[tokenId]/getTokenInfo.ts
Lunar Crush API is returning an inaccurate circulating supply for sBTC. Reverting the logic to use Stacks API holders endpoint for circulating supply just for sBTC.
> fix: fixed sbtc circulating supply

- src/app/token/[tokenId]/TokenInfo/MarketCap.tsx
- src/app/token/[tokenId]/TokenInfo/index.tsx
LunarCrush is returning an incorrect circulating supply for SBTC, resulting in an incorrect market cap. Manually overriding it here.
> fix: overriding marketcap

- src/app/token/[tokenId]/PageClient.tsx
Added array of legit sbtc derivatives whose token pages will not show a sbtc scam warning on them
The warning message had alignment issues and the font color was wrong on dark mode. I fixed those issue as well.
Sidenote:
We have 2 warning messages that are basically the same. Do we need both? or can I remove one?
"This token may be a scam. Engaging with unverified tokens could result in loss of funds."
This is triggered when the token is one of the risky tokens we've identified, such as
const RISKY_TOKENS = ['SP1J45NVEGQ7ZA4M57TGF0RAB00TMYCYG00X8EF5B.granite-btc'];
"This is not the official sBTC token and may be a scam. Engaging with unverified tokens could result in loss of funds."
This is triggered when sBTC is in the name and it's not original, genuine SBTC
> feat: marked zBTC as safe

- src/features/search/dropdown/search-results-card.tsx
Return null when entity url exists to prevent rendering results card after redirect
> fix: search: return null when entity url exists

- src/app/_components/Providers.tsx
- src/features/search/items/address-result-item.tsx
- src/ui/icons/WalletIcon.tsx
Fixes bug that causes crash due to the content not being wrapped by a chakra provider (production error), or a React element having more than a single child component (local error)
The issue was with the wallet icon which was not rendering correctly. Refactoring it into a phosphor icon and using the usual icon structure fixed this issue
Slack context: https://hiropbc.slack.com/archives/C03TU42NL05/p1739474432135939
> feat: fixed chakra provider missing/single child issue

- src/app/sandbox/deploy/LeftSection.tsx
This save contract feature won't be available anymore in the platform. This PR just removes it.
> fix: remove save contract

- src/stories/Typography/TextStyle.stories.tsx
- src/ui/theme/letterSpacings.ts
- src/ui/theme/textStyles.ts
- src/ui/theme/theme.ts
- Fix text styles
- Add letter spacings
closes #2018
> fix: text styles

- src/ui/theme/recipes/ButtonRecipe.ts
There was a regression with the "Add a Network" button in the settings dropdown. This fixes it. Somehow, the padding styles were removed from the button recipe
> fix: fixed small button recipe

- .github/workflows/deploy.yml
This change passes the appropriate secrets downstream to the composite Github action workflow needed for automated GPG signing of all CI/CD commits.
> feat: sign bot commits

- src/app/_components/Search/ResultItem.tsx
The current effect removes the background on hover, which feels broken.
Proposal: use surface-fifth from the design system as the hover background to keep it consistent and readable.
closes https://github.com/hirosystems/explorer/issues/2260
> fix: change result item bg color on hover

- src/app/signers/PageClient.tsx
- src/app/signers/SignersHeader.tsx
- src/app/signers/page.tsx
- src/app/signers/skeleton.tsx
**Summary**
- Removed the stacking section from the Signers page so it now focuses solely on signer data. The simplified header is shown in SignersHeader.tsx where only signer distribution and map elements remain
- Updated the skeleton file to match the new layout, ensuring the placeholder header renders only signer distribution data
- Dropped the token price dependency and simplified the client component and route; the page now simply renders <SignersHeader /> without fetching additional data
**Implementation Notes**
- Stacking-related card components were removed from the header layout but kept in the repository for potential reuse.
- Signers page loading states were adjusted to match the trimmed component tree.
The change addresses issue #2222.
**Files Changed**
- …
> Remove stacking section from signers page

- src/app/_components/RecentBlocks/RecentBtcBlocks.tsx
This is a similar issue to the one we faced in TxsTable.tsx where react query cache takes precedence over the initial data causing flickering and hydration issue.
closes #2216
> fix: recent blocks caching

- src/app/_components/NetworkOverview/ChartTooltip.tsx
- src/app/_components/NetworkOverview/NetworkOverview.tsx
- src/app/_components/NetworkOverview/__tests__/ChartTooltip.test.tsx
- src/app/data.ts
- add explanatory text to Network Overview tooltip
- test ChartTooltip renders new timeframe text
Fixes #2215
- leverage existing typography and colors for the extra tooltip line
- use renderWithProviders in tests to satisfy cookies/context requirements
- `pnpm lint`
- `pnpm test:unit`
- `pnpm build` *(fails: connect EHOSTUNREACH 172.24.0.3:8080)*
> Clarify network overview tooltip timeframe

- src/app/_components/RecentBlocks/BtcBlock.tsx
- src/app/_components/RecentBlocks/StxBlock.tsx
Fixing recent blocks links so they do not open a new tab 
closes https://github.com/hirosystems/explorer/issues/2199
> fix: recent block links do not open a new tab

- src/app/_components/RecentBlocks/BtcBlock.tsx
- src/app/_components/RecentBlocks/StxBlock.tsx
Switches the timestamps on the recent blocks section from 12 hour format to relative time
closes https://github.com/hirosystems/explorer/issues/2200
> fix: switch recent block timestamps to relative time

- src/app/_components/RecentBlocks/BtcBlock.tsx
- src/ui/theme/recipes/LinkRecipe.ts
Removed recent blocks default underline and only show it on hover
closes https://github.com/hirosystems/explorer/issues/2202
> chore: removed recent blocks underline and show it only on hover

- src/app/_components/TxsSection.tsx
- src/common/components/table/table-examples/TxsTable.tsx
- src/common/utils/time-utils.ts
Fixes the tx page timestamps showing in utc due to being server rendered by switching them to relative time
> fix: fixed tx page table timestamps

- package.json
- pnpm-lock.yaml
- src/app/address/[principal]/TokenBalanceCard/NftBalance.tsx
- src/app/address/[principal]/TokenBalanceCard/index.tsx
- src/app/address/[principal]/TokenBalanceCard/useBnsNames.ts
- src/app/transactions/page.tsx
- src/common/components/table/filters/address-filter/AddressFilterForm.tsx
- src/common/constants/constants.ts
- src/common/queries/bns-queries.ts
- src/common/queries/useConfirmedTransactionsInfinite.ts
- src/common/queries/useSearchQuery.ts
- src/common/utils/utils.ts
- Update search to resolve BNSv2 names instead of BNSv1
- Replace Stacks API BNS name resolution with bns-v2-sdk library
- Support more BNS extensions: .btc, .locker, .stx & .id
- Support BNSv2 extensions in advance search
- Display BNSv2 name under address holdings section
closes #1906
> feat: support BNSv2

- src/app/sandbox/deploy/LeftSection.tsx
- src/app/sandbox/utils/walletTransactions.ts
I'm hoping this is all that is needed to make the sandbox use Clarity 3 for contract deployments. This would solve confusion from users, since most are expecting to deploy using the latest version of Clarity.
> feat: default to deploy using Clarity 3

- src/app/txid/[txId]/PageClient.tsx
- src/app/txid/[txId]/page-data.ts
Slack context here: https://hiropbc.slack.com/archives/C03TU42NL05/p1756141645153409
Reducing the cache time on tx id pages to reduce inconsistencies in tx status perhaps due to the complexity of maintaining a 10 min cache time for confirmed txs and relying on client revalidation for pending txs
Link to smoke test: https://grafana.stg.hiro.tools/d/k6_prometheus/k6-prometheus?orgId=1&from=now-3h&to=now&timezone=browser&var-DS_PROMETHEUS=mimir&var-testid=$__all&var-quantile_stat=p99&var-adhoc_filter=
> feat: reduced the cache time to 3 sec and removed revalidation

- src/app/_components/RecentBlocks/NewBlockPlaceholder.tsx
- src/app/_components/RecentBlocks/RecentBlocks.tsx
- src/app/_components/RecentBlocks/RecentBtcBlocks.tsx
- src/app/_components/RecentBlocks/RecentStxBlocks.tsx
- src/app/_components/RecentBlocks/StxBlock.tsx
- src/app/_components/RecentBlocks/useRecentBlocks.ts
- src/app/blocks/queries/useBlocksV2Queries.ts
- src/app/context.tsx
- src/app/data.ts
- src/app/page.tsx
- src/common/components/table/table-examples/TxsTable.tsx
- src/common/queries/useBlockListInfinite.ts
- src/common/queries/useBurnBlocksInfinite.ts
Fixes the problem with the recent blocks widget where the stacks blocks section doesn't start a blocks subscrption.
I think there were a number of issues: no memoizing, using infinity, and trying to maintain two blocks subscriptions at the same time.
What I've done is combine all the data and subscription logic for the btc blocks and stacks blocks section into one hook.
This makes it easier to see how the subscription is being handled and to ensure there is only one happening at any single point in time.
> fix: home page blocks widget
